import PDFDocument from 'pdfkit';

export async function generateAssessmentPDF(patientInfo, assessment) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      const buffers = [];

      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => {
        const pdfData = Buffer.concat(buffers);
        resolve(pdfData);
      });

      // Header
      doc.fillColor('#000000').fontSize(24).text('SORA Fertility Network', { align: 'center' });
      doc.moveDown(0.5);
      doc.fontSize(14).fillColor('#666666').text('FertiSTAT Assessment Report', { align: 'center' });
      doc.moveDown(2);

      // Patient Info
      doc.fontSize(16).fillColor('#000000').text('Patient Information', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(12).fillColor('#333333');
      doc.text(`Name: ${patientInfo.name || 'Not Provided'}`);
      doc.text(`Email: ${patientInfo.email || 'Not Provided'}`);
      doc.text(`Phone: ${patientInfo.phone || 'Not Provided'}`);
      doc.text(`Age: ${patientInfo.age || 'Not Provided'}`);
      doc.moveDown(2);

      // Assessment Result
      doc.fontSize(16).fillColor('#000000').text('Assessment Results', { underline: true });
      doc.moveDown(0.5);
      
      let riskColor = '#16a34a'; // Green
      if (assessment.category === 'medium') riskColor = '#d97706'; // Amber
      if (assessment.category === 'high') riskColor = '#dc2626'; // Red

      doc.fontSize(18).fillColor(riskColor).text(`Risk Band: ${assessment.category.toUpperCase()}`);
      doc.moveDown(0.5);
      doc.fontSize(12).fillColor('#333333').text(assessment.detailedMeaning);
      doc.moveDown();
      doc.fontSize(12).fillColor('#111111').text(`Recommendation: ${assessment.recommendation}`, { stroke: true });
      doc.moveDown(2);

      // Flagged Factors
      if (assessment.flaggedFactors && assessment.flaggedFactors.length > 0) {
        doc.fontSize(16).fillColor('#000000').text('Flagged Factors', { underline: true });
        doc.moveDown(0.5);
        
        assessment.flaggedFactors.forEach(factor => {
          const factorColor = factor.level === 'red' ? '#dc2626' : '#d97706';
          doc.fontSize(12).fillColor(factorColor).text(`• ${factor.title} (${factor.level.toUpperCase()})`);
          doc.fontSize(10).fillColor('#555555').text(`  ${factor.detail}`);
          doc.moveDown(0.5);
        });
      }

      // Triggers
      if (assessment.referralTriggers && assessment.referralTriggers.length > 0) {
        doc.addPage();
        doc.fontSize(16).fillColor('#000000').text('Referral Triggers', { underline: true });
        doc.moveDown(0.5);
        
        assessment.referralTriggers.forEach(trigger => {
          doc.fontSize(12).fillColor('#dc2626').text(`• ${trigger}`);
          doc.moveDown(0.5);
        });
      }

      // Footer
      const bottom = doc.page.margins.bottom;
      doc.page.margins.bottom = 0;
      doc.text(
        'This report is generated by SORA Fertility Network and is intended for clinical context, not as a standalone diagnosis.',
        50,
        doc.page.height - 50,
        {
          lineBreak: false,
          align: 'center',
          color: '#999999'
        }
      );
      doc.page.margins.bottom = bottom;

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}
