import React from 'react';
import {
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip as RechartsTooltip,
  PieChart, Pie, Cell, AreaChart, Area
} from 'recharts';
import { 
  AlertCircle, CheckCircle2, AlertTriangle, Calendar, 
  Activity, HeartPulse, FileText, Droplets, ShieldAlert,
  ShieldCheck, Stethoscope
} from 'lucide-react';

const PAGE_STYLE = {
  width: '794px',
  height: '1123px',
  backgroundColor: '#ffffff',
  position: 'relative',
  overflow: 'hidden',
  boxSizing: 'border-box',
  fontFamily: 'system-ui, -apple-system, sans-serif',
  margin: '0',
  padding: '0'
};

const Header = ({ pageNum, title, reportSettings }) => {
  const isWhiteLabel = reportSettings?.whiteLabel;
  const logoUrl = reportSettings?.customLogoUrl;
  const clinicName = isWhiteLabel ? (reportSettings?.clinicName || "Clinic Report") : "SORA Fertility";
  
  return (
    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', borderBottom: '2px solid #5F7D67', paddingBottom: '16px', marginBottom: '32px', paddingTop: '32px', paddingLeft: '48px', paddingRight: '48px' }}>
      <div>
        {logoUrl ? (
          <img src={logoUrl} alt={clinicName} style={{ height: '40px', objectFit: 'contain' }} />
        ) : (
          <h1 style={{ fontSize: '30px', fontFamily: 'Georgia, serif', color: '#1F2B22', fontWeight: 'bold', margin: 0 }}>{clinicName}</h1>
        )}
        <p style={{ color: '#5F7D67', fontSize: '12px', fontWeight: 'bold', letterSpacing: '2px', textTransform: 'uppercase', margin: '4px 0 0 0' }}>Premium Clinical Report</p>
      </div>
      <div style={{ textAlign: 'right' }}>
        <h2 style={{ color: '#1F2B22', fontSize: '20px', fontWeight: '500', margin: 0 }}>{title}</h2>
        <p style={{ color: '#9ca3af', fontSize: '14px', margin: '4px 0 0 0' }}>Page {pageNum} of 5</p>
      </div>
    </div>
  );
};

const Footer = ({ reportSettings }) => {
  const isWhiteLabel = reportSettings?.whiteLabel;
  return (
    <div style={{ position: 'absolute', bottom: 0, left: 0, width: '100%', height: '64px', backgroundColor: '#FAF9F6', borderTop: '1px solid #e3e7e2', display: 'flex', justifyContent: 'space-between', alignItems: 'center', paddingLeft: '48px', paddingRight: '48px', boxSizing: 'border-box' }}>
      <p style={{ color: '#63716b', fontSize: '12px', margin: 0 }}>{isWhiteLabel ? 'Generated by Clinic' : 'Generated by SORA Fertility Systems &copy; 2026'}</p>
      <p style={{ color: '#63716b', fontSize: '12px', margin: 0 }}>Not a medical diagnosis. Consult your healthcare provider.</p>
    </div>
  );
};

const PatientDemographics = ({ leadName, formData, results }) => {
  return (
    <div style={{ display: 'flex', gap: '24px', paddingLeft: '48px', paddingRight: '48px', marginBottom: '32px' }}>
      <div style={{ flex: 1, backgroundColor: '#FAF9F6', padding: '24px', borderRadius: '12px', border: '1px solid #e3e7e2' }}>
        <h3 style={{ fontSize: '14px', fontWeight: 'bold', color: '#5F7D67', textTransform: 'uppercase', letterSpacing: '1px', marginBottom: '16px', borderBottom: '1px solid #e3e7e2', paddingBottom: '8px', marginTop: 0 }}>Patient Profile</h3>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between' }}><span style={{ color: '#6b7280', fontSize: '14px' }}>Full Name</span><span style={{ fontWeight: '600', color: '#1F2B22' }}>{leadName || 'Patient'}</span></div>
          <div style={{ display: 'flex', justifyContent: 'space-between' }}><span style={{ color: '#6b7280', fontSize: '14px' }}>Age</span><span style={{ fontWeight: '600', color: '#1F2B22' }}>{formData.age} Years</span></div>
          <div style={{ display: 'flex', justifyContent: 'space-between' }}><span style={{ color: '#6b7280', fontSize: '14px' }}>BMI</span><span style={{ fontWeight: '600', color: '#1F2B22' }}>{formData.bmi || 'N/A'} kg/m²</span></div>
          <div style={{ display: 'flex', justifyContent: 'space-between' }}><span style={{ color: '#6b7280', fontSize: '14px' }}>Current Goal</span><span style={{ fontWeight: '600', color: '#1F2B22', textTransform: 'capitalize' }}>{formData.tryingStatus === 'active' ? 'Actively Trying' : formData.tryingStatus}</span></div>
        </div>
      </div>
      <div style={{ flex: 1, backgroundColor: '#FAF9F6', padding: '24px', borderRadius: '12px', border: '1px solid #e3e7e2' }}>
        <h3 style={{ fontSize: '14px', fontWeight: 'bold', color: '#5F7D67', textTransform: 'uppercase', letterSpacing: '1px', marginBottom: '16px', borderBottom: '1px solid #e3e7e2', paddingBottom: '8px', marginTop: 0 }}>Clinical Triage Result</h3>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between' }}><span style={{ color: '#6b7280', fontSize: '14px' }}>Overall Risk Band</span>
            <span style={{ fontWeight: 'bold', textTransform: 'capitalize', color: results.category === 'high' ? '#a93f3f' : results.category === 'medium' ? '#d39a27' : '#42734c' }}>
              {results.category}
            </span>
          </div>
          <div style={{ display: 'flex', justifyContent: 'space-between' }}><span style={{ color: '#6b7280', fontSize: '14px' }}>Red Markers</span><span style={{ fontWeight: '600', color: '#a93f3f' }}>{results.redCount}</span></div>
          <div style={{ display: 'flex', justifyContent: 'space-between' }}><span style={{ color: '#6b7280', fontSize: '14px' }}>Amber Markers</span><span style={{ fontWeight: '600', color: '#d39a27' }}>{results.amberCount}</span></div>
          <div style={{ display: 'flex', justifyContent: 'space-between' }}><span style={{ color: '#6b7280', fontSize: '14px' }}>Referral Urgency</span><span style={{ fontWeight: '600', color: '#1F2B22' }}>{results.urgency.split(' ')[0]}</span></div>
        </div>
      </div>
    </div>
  );
};

export default function PremiumReportTemplate({ results, formData, leadName }) {
  if (!results) return null;

  // --- CHART DATA PREP ---
  const riskColor = results.category === "high" ? "#a93f3f" : (results.category === "medium" ? "#d39a27" : "#42734c");
  const riskBg = results.category === "high" ? "#fae9e7" : (results.category === "medium" ? "#fff1d9" : "#e8f3ea");
  
  const gaugeData = [
    { name: 'Score', value: results.category === 'high' ? 85 : results.category === 'medium' ? 50 : 15 },
    { name: 'Remainder', value: results.category === 'high' ? 15 : results.category === 'medium' ? 50 : 85 }
  ];

  const categories = {
    Lifestyle: ['smoking', 'alcohol', 'recreationalDrugs', 'caffeine', 'bmi'],
    Medical: ['thyroid', 'diabetes', 'tbHistory', 'tbTreatment', 'cancerTreatment', 'stiHistory'],
    Menstrual: ['cycleReg', 'cycleLength', 'pcos', 'endo', 'pelvicPain'],
    History: ['prevBirth', 'pregnancyLosses', 'ectopicPregnancy', 'pelvicSurgery', 'uterineHistory', 'familyEarlyMenopause']
  };

  const getCategoryCount = (catName) => {
    return results.flaggedFactors.filter(f => categories[catName]?.includes(f.key)).length;
  };

  const barChartData = [
    { name: 'Lifestyle', count: getCategoryCount('Lifestyle') },
    { name: 'Medical', count: getCategoryCount('Medical') },
    { name: 'Menstrual', count: getCategoryCount('Menstrual') },
    { name: 'History', count: getCategoryCount('History') }
  ];

  const ageData = [
    { age: '25', fertility: 90 },
    { age: '30', fertility: 80 },
    { age: '35', fertility: 60 },
    { age: '38', fertility: 40 },
    { age: '40', fertility: 25 },
    { age: '42', fertility: 10 },
    { age: '45', fertility: 2 },
  ];

  const renderIcon = (level) => {
    if (level === 'red') return <AlertTriangle style={{ color: '#a93f3f', width: '20px', height: '20px', flexShrink: 0, marginTop: '2px' }} />;
    if (level === 'amber') return <AlertCircle style={{ color: '#d39a27', width: '20px', height: '20px', flexShrink: 0, marginTop: '2px' }} />;
    return <CheckCircle2 style={{ color: '#42734c', width: '20px', height: '20px', flexShrink: 0, marginTop: '2px' }} />;
  };

  return (
    <div id="premium-report-container" style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', backgroundColor: '#f3f4f6' }}>
      
      {/* PAGE 1 */}
      <div className="report-page" style={PAGE_STYLE}>
        <Header pageNum={1} title="Executive Summary" reportSettings={reportSettings} />
        <PatientDemographics leadName={leadName} formData={formData} results={results} />

        <div style={{ paddingLeft: '48px', paddingRight: '48px', marginBottom: '32px' }}>
          <div style={{ backgroundColor: riskBg, border: `1px solid ${riskColor}40`, padding: '32px', borderRadius: '16px', display: 'flex', alignItems: 'center', gap: '40px' }}>
            <div style={{ width: '33%', display: 'flex', justifyContent: 'center', position: 'relative' }}>
              <PieChart width={200} height={200}>
                <Pie data={gaugeData} cx={100} cy={100} startAngle={180} endAngle={0} innerRadius={70} outerRadius={90} dataKey="value" stroke="none">
                  <Cell fill={riskColor} />
                  <Cell fill="#edf0ed" />
                </Pie>
              </PieChart>
              <div style={{ position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', paddingTop: '32px' }}>
                <span style={{ fontSize: '30px', fontWeight: 'bold', color: riskColor }}>{results.category.toUpperCase()}</span>
                <span style={{ fontSize: '12px', fontWeight: 'bold', color: '#6b7280', textTransform: 'uppercase', letterSpacing: '2px', marginTop: '4px' }}>Risk Band</span>
              </div>
            </div>
            <div style={{ width: '66%' }}>
              <h2 style={{ fontSize: '24px', fontWeight: 'bold', marginBottom: '12px', color: riskColor, marginTop: 0 }}>Clinical Assessment</h2>
              <p style={{ color: '#1F2B22', fontSize: '18px', lineHeight: '1.6', marginBottom: '16px', marginTop: 0 }}>{results.detailedMeaning}</p>
              <div style={{ backgroundColor: 'rgba(255,255,255,0.6)', padding: '16px', borderRadius: '8px', border: `1px solid ${riskColor}30` }}>
                <p style={{ fontWeight: '600', fontSize: '14px', textTransform: 'uppercase', letterSpacing: '1px', marginBottom: '4px', color: '#6b7280', marginTop: 0 }}>Primary Recommendation</p>
                <p style={{ fontWeight: 'bold', color: '#1F2B22', fontSize: '18px', margin: 0 }}>{results.recommendation}</p>
              </div>
            </div>
          </div>
        </div>

        {results.triggers.length > 0 && (
          <div style={{ paddingLeft: '48px', paddingRight: '48px', marginBottom: '32px' }}>
            <h3 style={{ fontSize: '18px', fontWeight: 'bold', color: '#1F2B22', borderBottom: '1px solid #e5e7eb', paddingBottom: '8px', marginBottom: '16px', marginTop: 0 }}>Immediate Referral Triggers</h3>
            <ul style={{ listStyleType: 'none', padding: 0, margin: 0, display: 'flex', flexDirection: 'column', gap: '12px' }}>
              {results.triggers.map((trigger, idx) => (
                <li key={idx} style={{ display: 'flex', gap: '12px', backgroundColor: '#fef2f2', padding: '16px', borderRadius: '8px', border: '1px solid #fee2e2' }}>
                  <ShieldAlert style={{ color: '#a93f3f', flexShrink: 0, width: '24px', height: '24px' }} />
                  <span style={{ color: '#a93f3f', fontWeight: '500' }}>{trigger}</span>
                </li>
              ))}
            </ul>
          </div>
        )}
        <Footer reportSettings={reportSettings} />
      </div>

      {/* PAGE 2 */}
      <div className="report-page" style={PAGE_STYLE}>
        <Header pageNum={2} title="Risk Factor Analysis" reportSettings={reportSettings} />
        
        <div style={{ paddingLeft: '48px', paddingRight: '48px', marginBottom: '40px' }}>
          <h3 style={{ fontSize: '20px', fontWeight: 'bold', color: '#1F2B22', marginBottom: '24px', marginTop: 0 }}>Identified Risk Areas</h3>
          <div style={{ height: '250px', width: '100%' }}>
            <BarChart width={600} height={250} data={barChartData} layout="vertical" margin={{ top: 5, right: 30, left: 20, bottom: 5 }}>
              <CartesianGrid strokeDasharray="3 3" horizontal={false} />
              <XAxis type="number" allowDecimals={false} />
              <YAxis dataKey="name" type="category" width={80} tick={{ fill: '#1F2B22', fontWeight: 600 }} />
              <Bar dataKey="count" fill="#d39a27" radius={[0, 4, 4, 0]} barSize={30}>
                {barChartData.map((entry, index) => (
                  <Cell key={`cell-${index}`} fill={entry.count > 1 ? '#a93f3f' : entry.count === 1 ? '#d39a27' : '#5F7D67'} />
                ))}
              </Bar>
            </BarChart>
          </div>
          <p style={{ fontSize: '14px', color: '#6b7280', textAlign: 'center', marginTop: '8px', fontStyle: 'italic' }}>Number of flagged markers by clinical category</p>
        </div>

        <div style={{ paddingLeft: '48px', paddingRight: '48px' }}>
          <h3 style={{ fontSize: '20px', fontWeight: 'bold', color: '#1F2B22', borderBottom: '2px solid #5F7D67', paddingBottom: '8px', marginBottom: '24px', marginTop: 0 }}>Detailed Marker Breakdown</h3>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
            {results.flaggedFactors.length > 0 ? results.flaggedFactors.map((factor, idx) => (
              <div key={idx} style={{ display: 'flex', alignItems: 'flex-start', gap: '16px', padding: '16px', backgroundColor: '#FAF9F6', borderRadius: '12px', border: '1px solid #e3e7e2' }}>
                {renderIcon(factor.level)}
                <div>
                  <h4 style={{ fontWeight: 'bold', color: '#1F2B22', fontSize: '16px', margin: 0 }}>{factor.title}</h4>
                  <p style={{ fontSize: '14px', fontWeight: '500', marginTop: '4px', marginBottom: '8px', color: factor.level === 'red' ? '#a93f3f' : '#d39a27' }}>
                    {factor.label}
                  </p>
                  <p style={{ fontSize: '14px', color: '#63716b', lineHeight: '1.6', margin: 0 }}>{factor.detail}</p>
                </div>
              </div>
            )) : (
              <div style={{ display: 'flex', alignItems: 'center', gap: '12px', padding: '24px', backgroundColor: '#f0fdf4', border: '1px solid #dcfce7', borderRadius: '12px', color: '#166534' }}>
                <ShieldCheck style={{ width: '32px', height: '32px' }} />
                <p style={{ fontWeight: 'bold', fontSize: '18px', margin: 0 }}>No significant clinical risk markers identified.</p>
              </div>
            )}
          </div>
        </div>
        <Footer reportSettings={reportSettings} />
      </div>

      {/* PAGE 3 */}
      <div className="report-page" style={PAGE_STYLE}>
        <Header pageNum={3} title="Ovarian Reserve & Demographics" reportSettings={reportSettings} />
        
        {results.ovarianReserve ? (
          <div style={{ paddingLeft: '48px', paddingRight: '48px', marginBottom: '40px' }}>
            <h3 style={{ fontSize: '20px', fontWeight: 'bold', color: '#1F2B22', marginBottom: '16px', marginTop: 0 }}>Laboratory Calibration</h3>
            <div style={{ padding: '24px', backgroundColor: '#FAF9F6', border: '1px solid #e3e7e2', borderRadius: '12px', display: 'flex', alignItems: 'center', gap: '24px' }}>
              <div style={{ backgroundColor: '#e8f3ea', padding: '16px', borderRadius: '50%' }}>
                <Activity style={{ width: '48px', height: '48px', color: '#5F7D67' }} />
              </div>
              <div>
                <h4 style={{ fontSize: '24px', fontWeight: 'bold', color: '#1F2B22', marginTop: '4px', marginBottom: 0, textTransform: 'capitalize' }}>
                  {results.ovarianReserve.reserve} Reserve
                </h4>
                <p style={{ fontSize: '14px', color: '#63716b', marginTop: '8px', margin: 0 }}>
                  This result is a calculation based on the entered parameters. Discuss these values with a healthcare provider for a clinical interpretation.
                </p>
              </div>
            </div>
          </div>
        ) : (
          <div style={{ paddingLeft: '48px', paddingRight: '48px', marginBottom: '40px' }}>
            <h3 style={{ fontSize: '20px', fontWeight: 'bold', color: '#1F2B22', marginBottom: '16px', marginTop: 0 }}>Laboratory Calibration</h3>
            <div style={{ padding: '24px', backgroundColor: '#f9fafb', border: '1px solid #e5e7eb', borderRadius: '12px', display: 'flex', alignItems: 'center', gap: '24px' }}>
              <Droplets style={{ width: '40px', height: '40px', color: '#9ca3af' }} />
              <div>
                <p style={{ fontSize: '14px', fontWeight: 'bold', color: '#6b7280', textTransform: 'uppercase', margin: 0 }}>Labs Not Provided</p>
                <p style={{ fontSize: '14px', color: '#6b7280', marginTop: '4px', margin: 0 }}>Ovarian reserve testing (AMH, FSH, AFC) was skipped. Talk to your clinic about testing.</p>
              </div>
            </div>
          </div>
        )}

        <div style={{ paddingLeft: '48px', paddingRight: '48px', marginBottom: '40px' }}>
          <h3 style={{ fontSize: '20px', fontWeight: 'bold', color: '#1F2B22', marginBottom: '24px', marginTop: 0 }}>Statistical Fertility Decline by Age</h3>
          <p style={{ fontSize: '14px', color: '#63716b', marginBottom: '16px', marginTop: 0 }}>
            Female fertility naturally declines with age, primarily due to a decrease in egg quantity and quality. The chart below shows the statistical probability of natural conception over a year, compared to your current age ({formData.age}).
          </p>
          <div style={{ height: '300px', width: '100%', backgroundColor: '#FAF9F6', border: '1px solid #e3e7e2', borderRadius: '12px', padding: '16px', boxSizing: 'border-box' }}>
            <AreaChart width={650} height={260} data={ageData} margin={{ top: 10, right: 30, left: 0, bottom: 0 }}>
              <defs>
                <linearGradient id="colorFertility" x1="0" y1="0" x2="0" y2="1">
                  <stop offset="5%" stopColor="#5F7D67" stopOpacity={0.4}/>
                  <stop offset="95%" stopColor="#5F7D67" stopOpacity={0}/>
                </linearGradient>
              </defs>
              <XAxis dataKey="age" label={{ value: 'Age', position: 'insideBottomRight', offset: -5 }} />
              <YAxis label={{ value: 'Conception Probability (%)', angle: -90, position: 'insideLeft' }} />
              <CartesianGrid strokeDasharray="3 3" vertical={false} />
              <Area type="monotone" dataKey="fertility" stroke="#5F7D67" strokeWidth={3} fillOpacity={1} fill="url(#colorFertility)" />
            </AreaChart>
          </div>
        </div>
        <Footer reportSettings={reportSettings} />
      </div>

      {/* PAGE 4 */}
      <div className="report-page" style={PAGE_STYLE}>
        <Header pageNum={4} title="Action Plan & Timeline" reportSettings={reportSettings} />
        
        <div style={{ paddingLeft: '48px', paddingRight: '48px', marginBottom: '40px' }}>
          <h3 style={{ fontSize: '20px', fontWeight: 'bold', color: '#1F2B22', marginBottom: '24px', marginTop: 0 }}>Recommended Next Steps</h3>
          <div style={{ position: 'relative', borderLeft: '2px solid #5F7D67', marginLeft: '16px', paddingLeft: '32px', display: 'flex', flexDirection: 'column', gap: '32px' }}>
            
            <div style={{ position: 'relative' }}>
              <div style={{ position: 'absolute', left: '-43px', top: '0', width: '20px', height: '20px', backgroundColor: '#5F7D67', borderRadius: '50%', border: '4px solid #ffffff', boxSizing: 'content-box' }} />
              <h4 style={{ fontSize: '18px', fontWeight: 'bold', color: '#1F2B22', display: 'flex', alignItems: 'center', gap: '8px', margin: 0 }}><Calendar style={{ width: '20px', height: '20px' }}/> Immediate Actions</h4>
              <p style={{ color: '#63716b', fontSize: '14px', marginTop: '8px', lineHeight: '1.6', margin: '8px 0 0 0' }}>
                {results.category === 'high' ? 
                  "Schedule a consultation with a fertility specialist as soon as possible based on the flagged clinical triggers." : 
                  "Begin preconception vitamins (folic acid) and review lifestyle factors identified in the risk analysis."}
              </p>
            </div>
            
            <div style={{ position: 'relative' }}>
              <div style={{ position: 'absolute', left: '-43px', top: '0', width: '20px', height: '20px', backgroundColor: '#d39a27', borderRadius: '50%', border: '4px solid #ffffff', boxSizing: 'content-box' }} />
              <h4 style={{ fontSize: '18px', fontWeight: 'bold', color: '#1F2B22', display: 'flex', alignItems: 'center', gap: '8px', margin: 0 }}><Activity style={{ width: '20px', height: '20px' }}/> 3-6 Months</h4>
              <p style={{ color: '#63716b', fontSize: '14px', marginTop: '8px', lineHeight: '1.6', margin: '8px 0 0 0' }}>
                If conception has not occurred, or if you are planning for the future, consider baseline hormone testing (AMH, FSH) and a pelvic ultrasound. {formData.partnerSperm !== 'yes' && "A partner semen analysis should also be performed."}
              </p>
            </div>
            
            <div style={{ position: 'relative' }}>
              <div style={{ position: 'absolute', left: '-43px', top: '0', width: '20px', height: '20px', backgroundColor: '#a93f3f', borderRadius: '50%', border: '4px solid #ffffff', boxSizing: 'content-box' }} />
              <h4 style={{ fontSize: '18px', fontWeight: 'bold', color: '#1F2B22', display: 'flex', alignItems: 'center', gap: '8px', margin: 0 }}><Stethoscope style={{ width: '20px', height: '20px' }}/> 6-12 Months</h4>
              <p style={{ color: '#63716b', fontSize: '14px', marginTop: '8px', lineHeight: '1.6', margin: '8px 0 0 0' }}>
                A full specialist intervention may be necessary. Depending on ovarian reserve and age, treatments such as IUI or IVF might be discussed to maximize chances of success.
              </p>
            </div>

          </div>
        </div>

        <div style={{ paddingLeft: '48px', paddingRight: '48px' }}>
          <h3 style={{ fontSize: '20px', fontWeight: 'bold', color: '#1F2B22', marginBottom: '16px', marginTop: 0 }}>Preconception Checklist</h3>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
            <div style={{ padding: '16px', backgroundColor: '#FAF9F6', border: '1px solid #e3e7e2', borderRadius: '8px', display: 'flex', gap: '12px' }}>
              <HeartPulse style={{ width: '20px', height: '20px', color: '#5F7D67', marginTop: '2px' }} />
              <div>
                <span style={{ fontWeight: 'bold', display: 'block', fontSize: '14px' }}>Prenatal Vitamins</span>
                <span style={{ fontSize: '12px', color: '#6b7280', display: 'block', marginTop: '4px' }}>Take at least 400mcg of Folic Acid daily.</span>
              </div>
            </div>
            <div style={{ padding: '16px', backgroundColor: '#FAF9F6', border: '1px solid #e3e7e2', borderRadius: '8px', display: 'flex', gap: '12px' }}>
              <Activity style={{ width: '20px', height: '20px', color: '#5F7D67', marginTop: '2px' }} />
              <div>
                <span style={{ fontWeight: 'bold', display: 'block', fontSize: '14px' }}>Tracking</span>
                <span style={{ fontSize: '12px', color: '#6b7280', display: 'block', marginTop: '4px' }}>Monitor your cycles and fertile window.</span>
              </div>
            </div>
            <div style={{ padding: '16px', backgroundColor: '#FAF9F6', border: '1px solid #e3e7e2', borderRadius: '8px', display: 'flex', gap: '12px' }}>
              <AlertCircle style={{ width: '20px', height: '20px', color: '#5F7D67', marginTop: '2px' }} />
              <div>
                <span style={{ fontWeight: 'bold', display: 'block', fontSize: '14px' }}>Lifestyle Optimization</span>
                <span style={{ fontSize: '12px', color: '#6b7280', display: 'block', marginTop: '4px' }}>Limit caffeine, alcohol, and manage BMI.</span>
              </div>
            </div>
            <div style={{ padding: '16px', backgroundColor: '#FAF9F6', border: '1px solid #e3e7e2', borderRadius: '8px', display: 'flex', gap: '12px' }}>
              <Stethoscope style={{ width: '20px', height: '20px', color: '#5F7D67', marginTop: '2px' }} />
              <div>
                <span style={{ fontWeight: 'bold', display: 'block', fontSize: '14px' }}>Medical Review</span>
                <span style={{ fontSize: '12px', color: '#6b7280', display: 'block', marginTop: '4px' }}>Manage chronic conditions like Thyroid or Diabetes.</span>
              </div>
            </div>
          </div>
        </div>
        <Footer reportSettings={reportSettings} />
      </div>

      {/* PAGE 5 */}
      <div className="report-page" style={{ ...PAGE_STYLE, backgroundColor: '#FAF9F6' }}>
        <Header pageNum={5} title="Appendix & Glossary" reportSettings={reportSettings} />
        
        <div style={{ paddingLeft: '48px', paddingRight: '48px', marginBottom: '40px' }}>
          <h3 style={{ fontSize: '20px', fontWeight: 'bold', color: '#1F2B22', marginBottom: '24px', marginTop: 0 }}>Medical Glossary</h3>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
            <div style={{ backgroundColor: '#ffffff', padding: '16px', borderRadius: '12px', border: '1px solid #e3e7e2' }}>
              <h4 style={{ fontWeight: 'bold', color: '#5F7D67', margin: 0 }}>AMH (Anti-Müllerian Hormone)</h4>
              <p style={{ fontSize: '14px', color: '#63716b', margin: '4px 0 0 0' }}>A hormone produced by small follicles in the ovaries. It is used as an indicator of ovarian reserve (the number of eggs remaining).</p>
            </div>
            <div style={{ backgroundColor: '#ffffff', padding: '16px', borderRadius: '12px', border: '1px solid #e3e7e2' }}>
              <h4 style={{ fontWeight: 'bold', color: '#5F7D67', margin: 0 }}>FSH (Follicle-Stimulating Hormone)</h4>
              <p style={{ fontSize: '14px', color: '#63716b', margin: '4px 0 0 0' }}>A hormone that stimulates the growth of ovarian follicles. Elevated baseline levels often indicate diminishing ovarian reserve.</p>
            </div>
            <div style={{ backgroundColor: '#ffffff', padding: '16px', borderRadius: '12px', border: '1px solid #e3e7e2' }}>
              <h4 style={{ fontWeight: 'bold', color: '#5F7D67', margin: 0 }}>PCOS (Polycystic Ovary Syndrome)</h4>
              <p style={{ fontSize: '14px', color: '#63716b', margin: '4px 0 0 0' }}>A common hormonal disorder that can cause irregular periods, excess androgen levels, and polycystic ovaries, often impacting ovulation.</p>
            </div>
            <div style={{ backgroundColor: '#ffffff', padding: '16px', borderRadius: '12px', border: '1px solid #e3e7e2' }}>
              <h4 style={{ fontWeight: 'bold', color: '#5F7D67', margin: 0 }}>Ovarian Reserve</h4>
              <p style={{ fontSize: '14px', color: '#63716b', margin: '4px 0 0 0' }}>A term used to describe the reproductive potential left in a woman&apos;s two ovaries based on the number and quality of remaining eggs.</p>
            </div>
          </div>
        </div>

        <div style={{ paddingLeft: '48px', paddingRight: '48px', marginBottom: '40px' }}>
          <h3 style={{ fontSize: '20px', fontWeight: 'bold', color: '#1F2B22', marginBottom: '24px', marginTop: 0 }}>Clinical References</h3>
          <ul style={{ paddingLeft: '20px', margin: 0, color: '#63716b', fontSize: '14px', lineHeight: '1.6' }}>
            <li style={{ marginBottom: '8px' }}>American Society for Reproductive Medicine (ASRM) Practice Committee Guidelines.</li>
            <li style={{ marginBottom: '8px' }}>European Society of Human Reproduction and Embryology (ESHRE) recommendations for preconception care.</li>
            <li style={{ marginBottom: '8px' }}>Bunting, L., & Boivin, J. (2010). Development and preliminary validation of the fertility status awareness tool (FertiSTAT).</li>
          </ul>
        </div>

        <div style={{ position: 'absolute', bottom: '80px', left: '48px', right: '48px', backgroundColor: '#1F2B22', padding: '32px', borderRadius: '16px', textAlign: 'center' }}>
          <FileText style={{ width: '40px', height: '40px', color: '#FAF9F6', margin: '0 auto 16px auto', display: 'block' }} />
          <h2 style={{ color: '#FAF9F6', fontSize: '24px', fontFamily: 'Georgia, serif', fontWeight: 'bold', marginBottom: '8px', marginTop: 0 }}>SORA Fertility</h2>
          <p style={{ color: '#e3e7e2', fontSize: '14px', maxWidth: '400px', margin: '0 auto', lineHeight: '1.5' }}>
            This premium assessment is provided for your personal records and to facilitate meaningful conversations with your healthcare provider.
          </p>
        </div>

        <Footer reportSettings={reportSettings} />
      </div>

    </div>
  );
}
