import React from 'react';
import {
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip as RechartsTooltip,
  PieChart, Pie, Cell, AreaChart, Area
} from 'recharts';
import { 
  AlertCircle, CheckCircle2, AlertTriangle, Calendar, 
  Activity, HeartPulse, FileText, Droplets, ShieldAlert,
  ShieldCheck, Stethoscope, BookOpen, Sparkles, Moon, Sun, Apple, Leaf
} from 'lucide-react';

const PAGE_STYLE = {
  width: '794px',
  height: '1123px',
  backgroundColor: '#ffffff',
  position: 'relative',
  overflow: 'hidden',
  boxSizing: 'border-box',
  fontFamily: 'system-ui, -apple-system, sans-serif',
  margin: '0',
  padding: '0'
};

const Header = ({ pageNum, title, reportSettings, totalPages = 5 }) => {
  const isWhiteLabel = reportSettings?.whiteLabel;
  const logoUrl = reportSettings?.customLogoUrl || (isWhiteLabel ? null : "/sora-logo.png");
  const clinicName = isWhiteLabel ? (reportSettings?.clinicName || "Clinic Report") : "SORA Fertility";
  
  return (
    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', borderBottom: '3px solid #DFBA89', paddingBottom: '16px', marginBottom: '32px', paddingTop: '32px', paddingLeft: '48px', paddingRight: '48px', background: 'linear-gradient(to right, #FAF9F6, #ffffff)' }}>
      <div>
        {logoUrl ? (
          <img src={logoUrl} alt={clinicName} style={{ height: '40px', objectFit: 'contain' }} />
        ) : (
          <h1 style={{ fontSize: '30px', fontFamily: 'Georgia, serif', color: '#1F2B22', fontWeight: 'bold', margin: 0 }}>{clinicName}</h1>
        )}
        <p style={{ color: '#5F7D67', fontSize: '12px', fontWeight: 'bold', letterSpacing: '2px', textTransform: 'uppercase', margin: '4px 0 0 0' }}>Premium Clinical Report</p>
      </div>
      <div style={{ textAlign: 'right' }}>
        <h2 style={{ color: '#1F2B22', fontSize: '20px', fontWeight: '600', margin: 0 }}>{title}</h2>
        <p style={{ color: '#9ca3af', fontSize: '14px', margin: '4px 0 0 0', fontWeight: '500' }}>Page {pageNum} of {totalPages}</p>
      </div>
    </div>
  );
};

const Footer = ({ reportSettings }) => {
  const isWhiteLabel = reportSettings?.whiteLabel;
  return (
    <div style={{ position: 'absolute', bottom: 0, left: 0, width: '100%', height: '64px', backgroundColor: '#1F2B22', display: 'flex', justifyContent: 'space-between', alignItems: 'center', paddingLeft: '48px', paddingRight: '48px', boxSizing: 'border-box' }}>
      <p style={{ color: '#DFBA89', fontSize: '12px', margin: 0, fontWeight: '500' }}>{isWhiteLabel ? 'Generated by Clinic' : 'Generated by SORA Fertility Systems © 2026'}</p>
      <p style={{ color: '#FAF9F6', fontSize: '12px', margin: 0, opacity: 0.8 }}>Not a medical diagnosis. Consult your healthcare provider.</p>
    </div>
  );
};

const PatientDemographics = ({ leadName, formData, results }) => {
  return (
    <div style={{ display: 'flex', gap: '24px', paddingLeft: '48px', paddingRight: '48px', marginBottom: '32px' }}>
      <div style={{ flex: 1, background: 'linear-gradient(135deg, #FAF9F6 0%, #ffffff 100%)', padding: '24px', borderRadius: '16px', border: '1px solid #e3e7e2', boxShadow: '0 4px 12px rgba(0,0,0,0.03)' }}>
        <h3 style={{ fontSize: '14px', fontWeight: 'bold', color: '#5F7D67', textTransform: 'uppercase', letterSpacing: '1px', marginBottom: '16px', borderBottom: '1px solid #e3e7e2', paddingBottom: '8px', marginTop: 0 }}>Patient Profile</h3>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between' }}><span style={{ color: '#6b7280', fontSize: '14px' }}>Full Name</span><span style={{ fontWeight: '600', color: '#1F2B22' }}>{leadName || 'Patient'}</span></div>
          <div style={{ display: 'flex', justifyContent: 'space-between' }}><span style={{ color: '#6b7280', fontSize: '14px' }}>Age</span><span style={{ fontWeight: '600', color: '#1F2B22' }}>{formData.age} Years</span></div>
          <div style={{ display: 'flex', justifyContent: 'space-between' }}><span style={{ color: '#6b7280', fontSize: '14px' }}>BMI</span><span style={{ fontWeight: '600', color: '#1F2B22' }}>{formData.bmi || 'N/A'} kg/m²</span></div>
          <div style={{ display: 'flex', justifyContent: 'space-between' }}><span style={{ color: '#6b7280', fontSize: '14px' }}>Current Goal</span><span style={{ fontWeight: '600', color: '#1F2B22', textTransform: 'capitalize' }}>{formData.tryingStatus === 'active' ? 'Actively Trying' : formData.tryingStatus}</span></div>
        </div>
      </div>
      <div style={{ flex: 1, background: 'linear-gradient(135deg, #FAF9F6 0%, #ffffff 100%)', padding: '24px', borderRadius: '16px', border: '1px solid #e3e7e2', boxShadow: '0 4px 12px rgba(0,0,0,0.03)' }}>
        <h3 style={{ fontSize: '14px', fontWeight: 'bold', color: '#5F7D67', textTransform: 'uppercase', letterSpacing: '1px', marginBottom: '16px', borderBottom: '1px solid #e3e7e2', paddingBottom: '8px', marginTop: 0 }}>Clinical Triage Result</h3>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between' }}><span style={{ color: '#6b7280', fontSize: '14px' }}>Overall Risk Band</span>
            <span style={{ fontWeight: 'bold', textTransform: 'capitalize', color: results.category === 'high' ? '#a93f3f' : results.category === 'medium' ? '#d39a27' : '#42734c' }}>
              {results.category}
            </span>
          </div>
          <div style={{ display: 'flex', justifyContent: 'space-between' }}><span style={{ color: '#6b7280', fontSize: '14px' }}>Red Markers</span><span style={{ fontWeight: '600', color: '#a93f3f' }}>{results.redCount}</span></div>
          <div style={{ display: 'flex', justifyContent: 'space-between' }}><span style={{ color: '#6b7280', fontSize: '14px' }}>Amber Markers</span><span style={{ fontWeight: '600', color: '#d39a27' }}>{results.amberCount}</span></div>
          <div style={{ display: 'flex', justifyContent: 'space-between' }}><span style={{ color: '#6b7280', fontSize: '14px' }}>Referral Urgency</span><span style={{ fontWeight: '600', color: '#1F2B22' }}>{results.urgency.split(' ')[0]}</span></div>
        </div>
      </div>
    </div>
  );
};

export default function PremiumReportTemplate({ results, formData, leadName, reportSettings }) {
  if (!results) return null;

  // --- CHART DATA PREP ---
  const riskColor = results.category === "high" ? "#a93f3f" : (results.category === "medium" ? "#d39a27" : "#42734c");
  const riskBg = results.category === "high" ? "#fae9e7" : (results.category === "medium" ? "#fff1d9" : "#e8f3ea");
  
  const gaugeData = [
    { name: 'Score', value: results.category === 'high' ? 85 : results.category === 'medium' ? 50 : 15 },
    { name: 'Remainder', value: results.category === 'high' ? 15 : results.category === 'medium' ? 50 : 85 }
  ];

  const categories = {
    Lifestyle: ['smoking', 'alcohol', 'recreationalDrugs', 'caffeine', 'bmi'],
    Medical: ['thyroid', 'diabetes', 'tbHistory', 'tbTreatment', 'cancerTreatment', 'stiHistory'],
    Menstrual: ['cycleReg', 'cycleLength', 'pcos', 'endo', 'pelvicPain'],
    History: ['prevBirth', 'pregnancyLosses', 'ectopicPregnancy', 'pelvicSurgery', 'uterineHistory', 'familyEarlyMenopause']
  };

  const getCategoryCount = (catName) => {
    return results.flaggedFactors.filter(f => categories[catName]?.includes(f.key)).length;
  };

  const barChartData = [
    { name: 'Lifestyle', count: getCategoryCount('Lifestyle') },
    { name: 'Medical', count: getCategoryCount('Medical') },
    { name: 'Menstrual', count: getCategoryCount('Menstrual') },
    { name: 'History', count: getCategoryCount('History') }
  ];

  const ageData = [
    { age: '25', fertility: 90 },
    { age: '30', fertility: 80 },
    { age: '35', fertility: 60 },
    { age: '38', fertility: 40 },
    { age: '40', fertility: 25 },
    { age: '42', fertility: 10 },
    { age: '45', fertility: 2 },
  ];

  const renderIcon = (level) => {
    if (level === 'red') return <AlertTriangle style={{ color: '#a93f3f', width: '24px', height: '24px', flexShrink: 0, marginTop: '2px' }} />;
    if (level === 'amber') return <AlertCircle style={{ color: '#d39a27', width: '24px', height: '24px', flexShrink: 0, marginTop: '2px' }} />;
    return <CheckCircle2 style={{ color: '#42734c', width: '24px', height: '24px', flexShrink: 0, marginTop: '2px' }} />;
  };

  // --- DYNAMIC PAGINATION FOR FLAGGED FACTORS ---
  const chunkedFactors = [];
  const factorsPerPage = 4; // Max 4 factors per page to avoid clipping
  if (results.flaggedFactors.length > 0) {
    for (let i = 0; i < results.flaggedFactors.length; i += factorsPerPage) {
      chunkedFactors.push(results.flaggedFactors.slice(i, i + factorsPerPage));
    }
  } else {
    chunkedFactors.push([]); // Always have at least one chunk for the "no risk factors" message
  }

  // Calculate total pages
  // 1 (Summary) + chunkedFactors.length (Risk Factor pages) + 1 (Ovarian) + 1 (Action Plan) + 1 (Education) + 1 (Wellness) + 1 (Appendix)
  const totalPages = 1 + chunkedFactors.length + 1 + 1 + 1 + 1 + 1;
  let currentPage = 1;

  return (
    <div id="premium-report-container" style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', backgroundColor: '#e5e7eb', gap: '20px', padding: '20px' }}>
      
      {/* PAGE 1: Executive Summary */}
      <div className="report-page" style={PAGE_STYLE}>
        <Header pageNum={currentPage++} title="Executive Summary" reportSettings={reportSettings} totalPages={totalPages} />
        <PatientDemographics leadName={leadName} formData={formData} results={results} />

        <div style={{ paddingLeft: '48px', paddingRight: '48px', marginBottom: '32px' }}>
          <div style={{ background: `linear-gradient(135deg, ${riskBg} 0%, #ffffff 100%)`, border: `2px solid ${riskColor}40`, padding: '32px', borderRadius: '16px', display: 'flex', alignItems: 'center', gap: '40px', boxShadow: '0 8px 24px rgba(0,0,0,0.06)' }}>
            <div style={{ width: '33%', display: 'flex', justifyContent: 'center', position: 'relative' }}>
              <PieChart width={200} height={200}>
                <Pie data={gaugeData} cx={100} cy={100} startAngle={180} endAngle={0} innerRadius={70} outerRadius={90} dataKey="value" stroke="none">
                  <Cell fill={riskColor} />
                  <Cell fill="#edf0ed" />
                </Pie>
              </PieChart>
              <div style={{ position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', paddingTop: '32px' }}>
                <span style={{ fontSize: '30px', fontWeight: 'bold', color: riskColor, textShadow: '0 2px 4px rgba(0,0,0,0.1)' }}>{results.category.toUpperCase()}</span>
                <span style={{ fontSize: '12px', fontWeight: 'bold', color: '#6b7280', textTransform: 'uppercase', letterSpacing: '2px', marginTop: '4px' }}>Risk Band</span>
              </div>
            </div>
            <div style={{ width: '66%' }}>
              <h2 style={{ fontSize: '26px', fontFamily: 'Georgia, serif', fontWeight: 'bold', marginBottom: '12px', color: riskColor, marginTop: 0 }}>Clinical Assessment</h2>
              <p style={{ color: '#1F2B22', fontSize: '16px', lineHeight: '1.6', marginBottom: '20px', marginTop: 0 }}>{results.detailedMeaning}</p>
              <div style={{ backgroundColor: '#ffffff', padding: '20px', borderRadius: '12px', border: `1px solid ${riskColor}30`, boxShadow: '0 4px 12px rgba(0,0,0,0.04)' }}>
                <p style={{ fontWeight: '600', fontSize: '13px', textTransform: 'uppercase', letterSpacing: '1px', marginBottom: '6px', color: '#6b7280', marginTop: 0 }}>Primary Recommendation</p>
                <p style={{ fontWeight: 'bold', color: '#1F2B22', fontSize: '18px', margin: 0, lineHeight: '1.4' }}>{results.recommendation}</p>
              </div>
            </div>
          </div>
        </div>

        {results.triggers.length > 0 && (
          <div style={{ paddingLeft: '48px', paddingRight: '48px', marginBottom: '32px' }}>
            <h3 style={{ fontSize: '20px', fontWeight: 'bold', color: '#1F2B22', borderBottom: '2px solid #e5e7eb', paddingBottom: '8px', marginBottom: '16px', marginTop: 0 }}>Immediate Referral Triggers</h3>
            <ul style={{ listStyleType: 'none', padding: 0, margin: 0, display: 'flex', flexDirection: 'column', gap: '12px' }}>
              {results.triggers.map((trigger, idx) => (
                <li key={idx} style={{ display: 'flex', gap: '16px', background: 'linear-gradient(to right, #fef2f2, #ffffff)', padding: '16px 20px', borderRadius: '12px', border: '1px solid #fee2e2', boxShadow: '0 2px 8px rgba(169, 63, 63, 0.05)' }}>
                  <ShieldAlert style={{ color: '#a93f3f', flexShrink: 0, width: '24px', height: '24px' }} />
                  <span style={{ color: '#a93f3f', fontWeight: '600', fontSize: '16px' }}>{trigger}</span>
                </li>
              ))}
            </ul>
          </div>
        )}
        <Footer reportSettings={reportSettings} />
      </div>

      {/* PAGE 2(s): Risk Factor Analysis (Chunked) */}
      {chunkedFactors.map((chunk, chunkIndex) => (
        <div key={`risk-page-${chunkIndex}`} className="report-page" style={PAGE_STYLE}>
          <Header pageNum={currentPage++} title={`Risk Factor Analysis ${chunkedFactors.length > 1 ? `(Pt ${chunkIndex + 1})` : ''}`} reportSettings={reportSettings} totalPages={totalPages} />
          
          {chunkIndex === 0 && (
            <div style={{ paddingLeft: '48px', paddingRight: '48px', marginBottom: '32px' }}>
              <h3 style={{ fontSize: '22px', fontFamily: 'Georgia, serif', fontWeight: 'bold', color: '#1F2B22', marginBottom: '24px', marginTop: 0 }}>Identified Risk Areas</h3>
              <div style={{ height: '250px', width: '100%', backgroundColor: '#FAF9F6', borderRadius: '16px', border: '1px solid #e3e7e2', padding: '16px', boxSizing: 'border-box' }}>
                <BarChart width={600} height={220} data={barChartData} layout="vertical" margin={{ top: 5, right: 30, left: 20, bottom: 5 }}>
                  <CartesianGrid strokeDasharray="3 3" horizontal={false} stroke="#e5e7eb" />
                  <XAxis type="number" allowDecimals={false} stroke="#6b7280" />
                  <YAxis dataKey="name" type="category" width={80} tick={{ fill: '#1F2B22', fontWeight: 600 }} stroke="#6b7280" />
                  <RechartsTooltip cursor={{fill: 'transparent'}} contentStyle={{ borderRadius: '8px', border: 'none', boxShadow: '0 4px 12px rgba(0,0,0,0.1)' }} />
                  <Bar dataKey="count" fill="#DFBA89" radius={[0, 4, 4, 0]} barSize={24}>
                    {barChartData.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={entry.count > 1 ? '#a93f3f' : entry.count === 1 ? '#d39a27' : '#5F7D67'} />
                    ))}
                  </Bar>
                </BarChart>
              </div>
            </div>
          )}

          <div style={{ paddingLeft: '48px', paddingRight: '48px' }}>
            <h3 style={{ fontSize: '20px', fontWeight: 'bold', color: '#1F2B22', borderBottom: '3px solid #DFBA89', paddingBottom: '8px', marginBottom: '24px', marginTop: 0 }}>{chunkIndex === 0 ? 'Detailed Marker Breakdown' : 'Detailed Marker Breakdown (Cont.)'}</h3>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
              {chunk.length > 0 ? chunk.map((factor, idx) => (
                <div key={idx} style={{ display: 'flex', alignItems: 'flex-start', gap: '20px', padding: '20px', background: 'linear-gradient(to bottom right, #ffffff, #FAF9F6)', borderRadius: '16px', border: '1px solid #e3e7e2', boxShadow: '0 4px 12px rgba(0,0,0,0.02)' }}>
                  <div style={{ padding: '12px', backgroundColor: factor.level === 'red' ? '#fef2f2' : factor.level === 'amber' ? '#fffbeb' : '#f0fdf4', borderRadius: '12px' }}>
                    {renderIcon(factor.level)}
                  </div>
                  <div>
                    <h4 style={{ fontWeight: 'bold', color: '#1F2B22', fontSize: '18px', margin: 0 }}>{factor.title}</h4>
                    <p style={{ fontSize: '14px', fontWeight: '600', textTransform: 'uppercase', letterSpacing: '1px', marginTop: '6px', marginBottom: '10px', color: factor.level === 'red' ? '#a93f3f' : '#d39a27' }}>
                      {factor.label}
                    </p>
                    <p style={{ fontSize: '15px', color: '#63716b', lineHeight: '1.6', margin: 0 }}>{factor.detail}</p>
                  </div>
                </div>
              )) : (
                <div style={{ display: 'flex', alignItems: 'center', gap: '16px', padding: '24px', background: 'linear-gradient(to right, #f0fdf4, #ffffff)', border: '1px solid #dcfce7', borderRadius: '16px', color: '#166534', boxShadow: '0 4px 12px rgba(22, 101, 52, 0.05)' }}>
                  <ShieldCheck style={{ width: '32px', height: '32px' }} />
                  <p style={{ fontWeight: 'bold', fontSize: '18px', margin: 0 }}>Excellent! No significant clinical risk markers were identified.</p>
                </div>
              )}
            </div>
          </div>
          <Footer reportSettings={reportSettings} />
        </div>
      ))}

      {/* PAGE 3: Ovarian Reserve & Demographics */}
      <div className="report-page" style={PAGE_STYLE}>
        <Header pageNum={currentPage++} title="Ovarian Reserve & Demographics" reportSettings={reportSettings} totalPages={totalPages} />
        
        {results.ovarianReserve ? (
          <div style={{ paddingLeft: '48px', paddingRight: '48px', marginBottom: '40px' }}>
            <h3 style={{ fontSize: '22px', fontFamily: 'Georgia, serif', fontWeight: 'bold', color: '#1F2B22', marginBottom: '20px', marginTop: 0 }}>Laboratory Calibration</h3>
            <div style={{ padding: '32px', background: 'linear-gradient(135deg, #FAF9F6 0%, #ffffff 100%)', border: '1px solid #DFBA89', borderRadius: '16px', display: 'flex', alignItems: 'center', gap: '32px', boxShadow: '0 8px 24px rgba(223, 186, 137, 0.15)' }}>
              <div style={{ backgroundColor: '#1F2B22', padding: '20px', borderRadius: '50%' }}>
                <Activity style={{ width: '48px', height: '48px', color: '#DFBA89' }} />
              </div>
              <div>
                <h4 style={{ fontSize: '28px', fontWeight: 'bold', color: '#1F2B22', marginTop: '0', marginBottom: '8px', textTransform: 'capitalize' }}>
                  {results.ovarianReserve.reserve} Reserve
                </h4>
                <p style={{ fontSize: '15px', color: '#63716b', margin: 0, lineHeight: '1.6' }}>
                  This result is a sophisticated calculation based on your provided AMH, FSH, and AFC inputs. This provides a snapshot of remaining egg quantity, but does not dictate egg quality.
                </p>
              </div>
            </div>
          </div>
        ) : (
          <div style={{ paddingLeft: '48px', paddingRight: '48px', marginBottom: '40px' }}>
            <h3 style={{ fontSize: '22px', fontFamily: 'Georgia, serif', fontWeight: 'bold', color: '#1F2B22', marginBottom: '20px', marginTop: 0 }}>Laboratory Calibration</h3>
            <div style={{ padding: '32px', backgroundColor: '#f9fafb', border: '1px dashed #d1d5db', borderRadius: '16px', display: 'flex', alignItems: 'center', gap: '32px' }}>
              <div style={{ backgroundColor: '#e5e7eb', padding: '20px', borderRadius: '50%' }}>
                <Droplets style={{ width: '40px', height: '40px', color: '#9ca3af' }} />
              </div>
              <div>
                <p style={{ fontSize: '14px', fontWeight: 'bold', color: '#4b5563', textTransform: 'uppercase', letterSpacing: '1px', margin: '0 0 8px 0' }}>Labs Not Provided</p>
                <p style={{ fontSize: '15px', color: '#6b7280', margin: 0, lineHeight: '1.6' }}>Ovarian reserve testing (AMH, FSH, AFC) was skipped. Ask your clinician to perform these simple blood and ultrasound tests to establish your baseline.</p>
              </div>
            </div>
          </div>
        )}

        <div style={{ paddingLeft: '48px', paddingRight: '48px', marginBottom: '40px' }}>
          <h3 style={{ fontSize: '22px', fontFamily: 'Georgia, serif', fontWeight: 'bold', color: '#1F2B22', marginBottom: '16px', marginTop: 0 }}>Statistical Fertility Decline by Age</h3>
          <p style={{ fontSize: '15px', color: '#63716b', marginBottom: '24px', marginTop: 0, lineHeight: '1.6' }}>
            Female fertility naturally declines with age, primarily due to a decrease in egg quantity and quality. The chart below visualizes the statistical probability of natural conception over a 12-month period relative to your current age ({formData.age}).
          </p>
          <div style={{ height: '320px', width: '100%', background: 'linear-gradient(to bottom, #ffffff, #FAF9F6)', border: '1px solid #e3e7e2', borderRadius: '16px', padding: '24px', boxSizing: 'border-box', boxShadow: '0 4px 12px rgba(0,0,0,0.03)' }}>
            <AreaChart width={650} height={260} data={ageData} margin={{ top: 10, right: 30, left: 0, bottom: 0 }}>
              <defs>
                <linearGradient id="colorFertility" x1="0" y1="0" x2="0" y2="1">
                  <stop offset="5%" stopColor="#DFBA89" stopOpacity={0.6}/>
                  <stop offset="95%" stopColor="#DFBA89" stopOpacity={0.05}/>
                </linearGradient>
              </defs>
              <XAxis dataKey="age" label={{ value: 'Age', position: 'insideBottomRight', offset: -5 }} stroke="#6b7280" />
              <YAxis label={{ value: 'Conception Probability (%)', angle: -90, position: 'insideLeft' }} stroke="#6b7280" />
              <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e5e7eb" />
              <Area type="monotone" dataKey="fertility" stroke="#DFBA89" strokeWidth={4} fillOpacity={1} fill="url(#colorFertility)" />
            </AreaChart>
          </div>
        </div>
        <Footer reportSettings={reportSettings} />
      </div>

      {/* PAGE 4: Action Plan & Timeline */}
      <div className="report-page" style={PAGE_STYLE}>
        <Header pageNum={currentPage++} title="Action Plan & Timeline" reportSettings={reportSettings} totalPages={totalPages} />
        
        <div style={{ paddingLeft: '48px', paddingRight: '48px', marginBottom: '40px' }}>
          <h3 style={{ fontSize: '22px', fontFamily: 'Georgia, serif', fontWeight: 'bold', color: '#1F2B22', marginBottom: '32px', marginTop: 0 }}>Recommended Clinical Pathway</h3>
          <div style={{ position: 'relative', borderLeft: '3px solid #DFBA89', marginLeft: '16px', paddingLeft: '40px', display: 'flex', flexDirection: 'column', gap: '40px' }}>
            
            <div style={{ position: 'relative' }}>
              <div style={{ position: 'absolute', left: '-55px', top: '0', width: '24px', height: '24px', backgroundColor: '#DFBA89', borderRadius: '50%', border: '4px solid #ffffff', boxSizing: 'content-box', boxShadow: '0 2px 8px rgba(0,0,0,0.1)' }} />
              <h4 style={{ fontSize: '20px', fontWeight: 'bold', color: '#1F2B22', display: 'flex', alignItems: 'center', gap: '12px', margin: 0 }}><Calendar style={{ width: '24px', height: '24px', color: '#5F7D67' }}/> Immediate Actions</h4>
              <p style={{ color: '#4b5563', fontSize: '15px', marginTop: '12px', lineHeight: '1.6', margin: '12px 0 0 0', backgroundColor: '#FAF9F6', padding: '16px', borderRadius: '12px', border: '1px solid #e3e7e2' }}>
                {results.category === 'high' ? 
                  "Schedule a consultation with a fertility specialist as soon as possible based on the flagged clinical triggers." : 
                  "Begin preconception vitamins (folic acid) and review lifestyle factors identified in the risk analysis."}
              </p>
            </div>
            
            <div style={{ position: 'relative' }}>
              <div style={{ position: 'absolute', left: '-55px', top: '0', width: '24px', height: '24px', backgroundColor: '#DFBA89', borderRadius: '50%', border: '4px solid #ffffff', boxSizing: 'content-box', boxShadow: '0 2px 8px rgba(0,0,0,0.1)' }} />
              <h4 style={{ fontSize: '20px', fontWeight: 'bold', color: '#1F2B22', display: 'flex', alignItems: 'center', gap: '12px', margin: 0 }}><Activity style={{ width: '24px', height: '24px', color: '#5F7D67' }}/> 3-6 Months</h4>
              <p style={{ color: '#4b5563', fontSize: '15px', marginTop: '12px', lineHeight: '1.6', margin: '12px 0 0 0', backgroundColor: '#FAF9F6', padding: '16px', borderRadius: '12px', border: '1px solid #e3e7e2' }}>
                If conception has not occurred, or if you are planning for the future, consider baseline hormone testing (AMH, FSH) and a pelvic ultrasound. {formData.partnerSperm !== 'yes' && "A partner semen analysis should also be performed."}
              </p>
            </div>
            
            <div style={{ position: 'relative' }}>
              <div style={{ position: 'absolute', left: '-55px', top: '0', width: '24px', height: '24px', backgroundColor: '#DFBA89', borderRadius: '50%', border: '4px solid #ffffff', boxSizing: 'content-box', boxShadow: '0 2px 8px rgba(0,0,0,0.1)' }} />
              <h4 style={{ fontSize: '20px', fontWeight: 'bold', color: '#1F2B22', display: 'flex', alignItems: 'center', gap: '12px', margin: 0 }}><Stethoscope style={{ width: '24px', height: '24px', color: '#5F7D67' }}/> 6-12 Months</h4>
              <p style={{ color: '#4b5563', fontSize: '15px', marginTop: '12px', lineHeight: '1.6', margin: '12px 0 0 0', backgroundColor: '#FAF9F6', padding: '16px', borderRadius: '12px', border: '1px solid #e3e7e2' }}>
                A full specialist intervention may be necessary. Depending on ovarian reserve and age, treatments such as IUI or IVF might be discussed to maximize chances of success.
              </p>
            </div>
          </div>
        </div>

        <div style={{ paddingLeft: '48px', paddingRight: '48px' }}>
          <h3 style={{ fontSize: '22px', fontFamily: 'Georgia, serif', fontWeight: 'bold', color: '#1F2B22', marginBottom: '24px', marginTop: 0 }}>Preconception Checklist</h3>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px' }}>
            <div style={{ padding: '20px', background: 'linear-gradient(to bottom, #ffffff, #FAF9F6)', border: '1px solid #e3e7e2', borderRadius: '16px', display: 'flex', gap: '16px', boxShadow: '0 4px 12px rgba(0,0,0,0.03)' }}>
              <div style={{ backgroundColor: '#e8f3ea', padding: '10px', borderRadius: '10px', height: 'fit-content' }}>
                <HeartPulse style={{ width: '24px', height: '24px', color: '#5F7D67' }} />
              </div>
              <div>
                <span style={{ fontWeight: 'bold', display: 'block', fontSize: '16px', color: '#1F2B22' }}>Prenatal Vitamins</span>
                <span style={{ fontSize: '13px', color: '#6b7280', display: 'block', marginTop: '6px', lineHeight: '1.5' }}>Take at least 400mcg of Folic Acid daily to prevent neural tube defects.</span>
              </div>
            </div>
            <div style={{ padding: '20px', background: 'linear-gradient(to bottom, #ffffff, #FAF9F6)', border: '1px solid #e3e7e2', borderRadius: '16px', display: 'flex', gap: '16px', boxShadow: '0 4px 12px rgba(0,0,0,0.03)' }}>
              <div style={{ backgroundColor: '#e8f3ea', padding: '10px', borderRadius: '10px', height: 'fit-content' }}>
                <Calendar style={{ width: '24px', height: '24px', color: '#5F7D67' }} />
              </div>
              <div>
                <span style={{ fontWeight: 'bold', display: 'block', fontSize: '16px', color: '#1F2B22' }}>Cycle Tracking</span>
                <span style={{ fontSize: '13px', color: '#6b7280', display: 'block', marginTop: '6px', lineHeight: '1.5' }}>Monitor your cycles and ovulation to identify your fertile window.</span>
              </div>
            </div>
            <div style={{ padding: '20px', background: 'linear-gradient(to bottom, #ffffff, #FAF9F6)', border: '1px solid #e3e7e2', borderRadius: '16px', display: 'flex', gap: '16px', boxShadow: '0 4px 12px rgba(0,0,0,0.03)' }}>
              <div style={{ backgroundColor: '#e8f3ea', padding: '10px', borderRadius: '10px', height: 'fit-content' }}>
                <AlertCircle style={{ width: '24px', height: '24px', color: '#5F7D67' }} />
              </div>
              <div>
                <span style={{ fontWeight: 'bold', display: 'block', fontSize: '16px', color: '#1F2B22' }}>Lifestyle Optimization</span>
                <span style={{ fontSize: '13px', color: '#6b7280', display: 'block', marginTop: '6px', lineHeight: '1.5' }}>Limit caffeine, reduce alcohol, and aim for a balanced BMI.</span>
              </div>
            </div>
            <div style={{ padding: '20px', background: 'linear-gradient(to bottom, #ffffff, #FAF9F6)', border: '1px solid #e3e7e2', borderRadius: '16px', display: 'flex', gap: '16px', boxShadow: '0 4px 12px rgba(0,0,0,0.03)' }}>
              <div style={{ backgroundColor: '#e8f3ea', padding: '10px', borderRadius: '10px', height: 'fit-content' }}>
                <Stethoscope style={{ width: '24px', height: '24px', color: '#5F7D67' }} />
              </div>
              <div>
                <span style={{ fontWeight: 'bold', display: 'block', fontSize: '16px', color: '#1F2B22' }}>Medical Review</span>
                <span style={{ fontSize: '13px', color: '#6b7280', display: 'block', marginTop: '6px', lineHeight: '1.5' }}>Manage chronic conditions like Thyroid issues or Diabetes.</span>
              </div>
            </div>
          </div>
        </div>
        <Footer reportSettings={reportSettings} />
      </div>

      {/* NEW PAGE 5: Fertility 101 Educational Section */}
      <div className="report-page" style={PAGE_STYLE}>
        <Header pageNum={currentPage++} title="Fertility 101: Educational Guide" reportSettings={reportSettings} totalPages={totalPages} />
        
        <div style={{ paddingLeft: '48px', paddingRight: '48px', marginBottom: '32px' }}>
          <h3 style={{ fontSize: '22px', fontFamily: 'Georgia, serif', fontWeight: 'bold', color: '#1F2B22', marginBottom: '20px', marginTop: 0 }}>Understanding Your Biology</h3>
          <p style={{ fontSize: '15px', color: '#4b5563', lineHeight: '1.6', marginBottom: '24px', marginTop: 0 }}>Knowledge is power when it comes to your reproductive health. Here are the core concepts every individual should understand about their fertility journey.</p>
          
          <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
            <div style={{ padding: '24px', background: 'linear-gradient(to right, #1F2B22, #30473a)', color: '#ffffff', borderRadius: '16px', display: 'flex', gap: '20px', boxShadow: '0 8px 16px rgba(31, 43, 34, 0.15)' }}>
              <BookOpen style={{ width: '32px', height: '32px', color: '#DFBA89', flexShrink: 0 }} />
              <div>
                <h4 style={{ fontSize: '18px', fontWeight: 'bold', color: '#DFBA89', margin: '0 0 8px 0' }}>The Menstrual Cycle & Ovulation</h4>
                <p style={{ fontSize: '14px', margin: 0, lineHeight: '1.6', color: '#e3e7e2' }}>A typical cycle lasts 28 days, though 21-35 days is considered normal. Ovulation usually occurs around day 14. An egg survives for only 12-24 hours after release, making the "fertile window" (the 5 days before and the day of ovulation) critical for conception.</p>
              </div>
            </div>

            <div style={{ padding: '24px', background: '#FAF9F6', border: '1px solid #DFBA89', borderRadius: '16px', display: 'flex', gap: '20px' }}>
              <Activity style={{ width: '32px', height: '32px', color: '#5F7D67', flexShrink: 0 }} />
              <div>
                <h4 style={{ fontSize: '18px', fontWeight: 'bold', color: '#1F2B22', margin: '0 0 8px 0' }}>Ovarian Reserve: Quantity vs. Quality</h4>
                <p style={{ fontSize: '14px', margin: 0, lineHeight: '1.6', color: '#4b5563' }}><strong>Quantity:</strong> Measured by AMH and AFC, this tells us roughly how many eggs remain. It dictates how you might respond to IVF medications.<br/><br/><strong>Quality:</strong> Cannot be measured by a blood test. Age is the only true proxy for egg quality. As women age, the percentage of genetically normal eggs naturally decreases.</p>
              </div>
            </div>

            <div style={{ padding: '24px', background: '#FAF9F6', border: '1px solid #e3e7e2', borderRadius: '16px', display: 'flex', gap: '20px' }}>
              <Sparkles style={{ width: '32px', height: '32px', color: '#d39a27', flexShrink: 0 }} />
              <div>
                <h4 style={{ fontSize: '18px', fontWeight: 'bold', color: '#1F2B22', margin: '0 0 8px 0' }}>The Male Factor</h4>
                <p style={{ fontSize: '14px', margin: 0, lineHeight: '1.6', color: '#4b5563' }}>It takes two to conceive! Male factor infertility contributes to roughly 40-50% of all infertility cases. A simple semen analysis can evaluate sperm count, motility (movement), and morphology (shape). It is highly recommended that partners get tested early in the process.</p>
              </div>
            </div>
          </div>
        </div>
        <Footer reportSettings={reportSettings} />
      </div>

      {/* NEW PAGE 6: Personalized Wellness Plan */}
      <div className="report-page" style={PAGE_STYLE}>
        <Header pageNum={currentPage++} title="Lifestyle & Wellness Plan" reportSettings={reportSettings} totalPages={totalPages} />
        
        <div style={{ paddingLeft: '48px', paddingRight: '48px', marginBottom: '32px' }}>
          <h3 style={{ fontSize: '22px', fontFamily: 'Georgia, serif', fontWeight: 'bold', color: '#1F2B22', marginBottom: '24px', marginTop: 0 }}>Optimizing Your Body for Conception</h3>
          
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '24px' }}>
            <div style={{ padding: '24px', backgroundColor: '#ffffff', border: '1px solid #e3e7e2', borderRadius: '16px', boxShadow: '0 4px 12px rgba(0,0,0,0.03)' }}>
              <Apple style={{ width: '28px', height: '28px', color: '#5F7D67', marginBottom: '16px' }} />
              <h4 style={{ fontSize: '18px', fontWeight: 'bold', color: '#1F2B22', margin: '0 0 12px 0' }}>Nutrition & Diet</h4>
              <ul style={{ paddingLeft: '20px', margin: 0, color: '#6b7280', fontSize: '14px', lineHeight: '1.6' }}>
                <li style={{ marginBottom: '8px' }}><strong>Folic Acid/Folate:</strong> Essential for neural tube development.</li>
                <li style={{ marginBottom: '8px' }}><strong>Antioxidants:</strong> Berries, nuts, and dark leafy greens help protect egg quality.</li>
                <li><strong>Omega-3s:</strong> Found in salmon and walnuts, supportive of reproductive hormone production.</li>
              </ul>
            </div>

            <div style={{ padding: '24px', backgroundColor: '#ffffff', border: '1px solid #e3e7e2', borderRadius: '16px', boxShadow: '0 4px 12px rgba(0,0,0,0.03)' }}>
              <Moon style={{ width: '28px', height: '28px', color: '#5F7D67', marginBottom: '16px' }} />
              <h4 style={{ fontSize: '18px', fontWeight: 'bold', color: '#1F2B22', margin: '0 0 12px 0' }}>Sleep & Circadian Rhythm</h4>
              <ul style={{ paddingLeft: '20px', margin: 0, color: '#6b7280', fontSize: '14px', lineHeight: '1.6' }}>
                <li style={{ marginBottom: '8px' }}><strong>Melatonin:</strong> Critical for sleep, but also found in follicular fluid where it protects eggs from oxidative stress.</li>
                <li style={{ marginBottom: '8px' }}>Aim for 7-9 hours of uninterrupted sleep.</li>
                <li>Minimize blue light exposure 1 hour before bed to support natural hormone cycles.</li>
              </ul>
            </div>

            <div style={{ padding: '24px', backgroundColor: '#ffffff', border: '1px solid #e3e7e2', borderRadius: '16px', boxShadow: '0 4px 12px rgba(0,0,0,0.03)' }}>
              <Sun style={{ width: '28px', height: '28px', color: '#5F7D67', marginBottom: '16px' }} />
              <h4 style={{ fontSize: '18px', fontWeight: 'bold', color: '#1F2B22', margin: '0 0 12px 0' }}>Stress Management</h4>
              <ul style={{ paddingLeft: '20px', margin: 0, color: '#6b7280', fontSize: '14px', lineHeight: '1.6' }}>
                <li style={{ marginBottom: '8px' }}>High cortisol levels can disrupt the hypothalamus, which regulates ovulation.</li>
                <li style={{ marginBottom: '8px' }}>Incorporate mindfulness, yoga, or deep breathing exercises into your daily routine.</li>
              </ul>
            </div>

            <div style={{ padding: '24px', backgroundColor: '#ffffff', border: '1px solid #e3e7e2', borderRadius: '16px', boxShadow: '0 4px 12px rgba(0,0,0,0.03)' }}>
              <Leaf style={{ width: '28px', height: '28px', color: '#5F7D67', marginBottom: '16px' }} />
              <h4 style={{ fontSize: '18px', fontWeight: 'bold', color: '#1F2B22', margin: '0 0 12px 0' }}>Environmental Toxins</h4>
              <ul style={{ paddingLeft: '20px', margin: 0, color: '#6b7280', fontSize: '14px', lineHeight: '1.6' }}>
                <li style={{ marginBottom: '8px' }}><strong>Endocrine Disruptors:</strong> Avoid BPA (plastics) and Phthalates (fragrances/cosmetics) which can mimic hormones.</li>
                <li>Switch to glass food containers and clean, non-toxic household products where possible.</li>
              </ul>
            </div>
          </div>
        </div>
        <Footer reportSettings={reportSettings} />
      </div>

      {/* PAGE 7: Appendix & Glossary */}
      <div className="report-page" style={{ ...PAGE_STYLE, backgroundColor: '#FAF9F6' }}>
        <Header pageNum={currentPage++} title="Appendix & Glossary" reportSettings={reportSettings} totalPages={totalPages} />
        
        <div style={{ paddingLeft: '48px', paddingRight: '48px', marginBottom: '40px' }}>
          <h3 style={{ fontSize: '22px', fontFamily: 'Georgia, serif', fontWeight: 'bold', color: '#1F2B22', marginBottom: '24px', marginTop: 0 }}>Medical Glossary</h3>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
            <div style={{ backgroundColor: '#ffffff', padding: '20px', borderRadius: '16px', border: '1px solid #e3e7e2', boxShadow: '0 4px 12px rgba(0,0,0,0.02)' }}>
              <h4 style={{ fontWeight: 'bold', color: '#5F7D67', margin: 0, fontSize: '16px' }}>AMH (Anti-Müllerian Hormone)</h4>
              <p style={{ fontSize: '14px', color: '#63716b', margin: '8px 0 0 0', lineHeight: '1.6' }}>A hormone produced by small follicles in the ovaries. It is used as an indicator of ovarian reserve (the number of eggs remaining).</p>
            </div>
            <div style={{ backgroundColor: '#ffffff', padding: '20px', borderRadius: '16px', border: '1px solid #e3e7e2', boxShadow: '0 4px 12px rgba(0,0,0,0.02)' }}>
              <h4 style={{ fontWeight: 'bold', color: '#5F7D67', margin: 0, fontSize: '16px' }}>FSH (Follicle-Stimulating Hormone)</h4>
              <p style={{ fontSize: '14px', color: '#63716b', margin: '8px 0 0 0', lineHeight: '1.6' }}>A hormone that stimulates the growth of ovarian follicles. Elevated baseline levels often indicate diminishing ovarian reserve.</p>
            </div>
            <div style={{ backgroundColor: '#ffffff', padding: '20px', borderRadius: '16px', border: '1px solid #e3e7e2', boxShadow: '0 4px 12px rgba(0,0,0,0.02)' }}>
              <h4 style={{ fontWeight: 'bold', color: '#5F7D67', margin: 0, fontSize: '16px' }}>PCOS (Polycystic Ovary Syndrome)</h4>
              <p style={{ fontSize: '14px', color: '#63716b', margin: '8px 0 0 0', lineHeight: '1.6' }}>A common hormonal disorder that can cause irregular periods, excess androgen levels, and polycystic ovaries, often impacting ovulation.</p>
            </div>
            <div style={{ backgroundColor: '#ffffff', padding: '20px', borderRadius: '16px', border: '1px solid #e3e7e2', boxShadow: '0 4px 12px rgba(0,0,0,0.02)' }}>
              <h4 style={{ fontWeight: 'bold', color: '#5F7D67', margin: 0, fontSize: '16px' }}>Ovarian Reserve</h4>
              <p style={{ fontSize: '14px', color: '#63716b', margin: '8px 0 0 0', lineHeight: '1.6' }}>A term used to describe the reproductive potential left in a woman's two ovaries based on the number and quality of remaining eggs.</p>
            </div>
          </div>
        </div>

        <div style={{ paddingLeft: '48px', paddingRight: '48px', marginBottom: '40px' }}>
          <h3 style={{ fontSize: '20px', fontWeight: 'bold', color: '#1F2B22', marginBottom: '24px', marginTop: 0 }}>Clinical References</h3>
          <ul style={{ paddingLeft: '20px', margin: 0, color: '#63716b', fontSize: '14px', lineHeight: '1.6' }}>
            <li style={{ marginBottom: '8px' }}>American Society for Reproductive Medicine (ASRM) Practice Committee Guidelines.</li>
            <li style={{ marginBottom: '8px' }}>European Society of Human Reproduction and Embryology (ESHRE) recommendations for preconception care.</li>
            <li style={{ marginBottom: '8px' }}>Bunting, L., & Boivin, J. (2010). Development and preliminary validation of the fertility status awareness tool (FertiSTAT).</li>
          </ul>
        </div>

        <div style={{ position: 'absolute', bottom: '80px', left: '48px', right: '48px', background: 'linear-gradient(135deg, #1F2B22 0%, #30473a 100%)', padding: '40px', borderRadius: '20px', textAlign: 'center', boxShadow: '0 12px 32px rgba(31, 43, 34, 0.2)' }}>
          <FileText style={{ width: '48px', height: '48px', color: '#DFBA89', margin: '0 auto 20px auto', display: 'block' }} />
          <h2 style={{ color: '#FAF9F6', fontSize: '28px', fontFamily: 'Georgia, serif', fontWeight: 'bold', marginBottom: '12px', marginTop: 0 }}>SORA Fertility</h2>
          <p style={{ color: '#e3e7e2', fontSize: '15px', maxWidth: '450px', margin: '0 auto', lineHeight: '1.6' }}>
            This premium assessment is provided for your personal records and to facilitate meaningful, data-driven conversations with your healthcare provider.
          </p>
        </div>

        <Footer reportSettings={reportSettings} />
      </div>

    </div>
  );
}
