import React, { useEffect, useState } from 'react';
import {
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip as RechartsTooltip,
  PieChart, Pie, Cell, AreaChart, Area
} from 'recharts';
import { 
  AlertCircle, CheckCircle2, AlertTriangle, Calendar, 
  Activity, HeartPulse, FileText, Droplets, ShieldAlert,
  ShieldCheck, Stethoscope, BookOpen, Sparkles, Moon, Sun, Apple, Leaf
} from 'lucide-react';

const PAGE_STYLE = {
  width: '794px',
  height: '1123px',
  backgroundColor: '#ffffff',
  position: 'relative',
  overflow: 'hidden',
  boxSizing: 'border-box',
  fontFamily: 'system-ui, -apple-system, sans-serif',
  margin: '0',
  padding: '0'
};

const Header = ({ pageNum, title, reportSettings, totalPages = 5 }) => {
  const [baseUrl, setBaseUrl] = useState('');
  
  useEffect(() => {
    if (typeof window !== 'undefined') {
      setBaseUrl(window.location.origin);
    }
  }, []);

  const isWhiteLabel = reportSettings?.whiteLabel;
  // Use absolute URL to guarantee html2canvas can fetch the image without CORS/relative path issues
  const logoUrl = reportSettings?.customLogoUrl || (isWhiteLabel ? null : (baseUrl ? `${baseUrl}/sora-logo.png` : null));
  const clinicName = isWhiteLabel ? (reportSettings?.clinicName || "Clinic Report") : "SORA Fertility";
  
  return (
    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', borderBottom: '3px solid #ff2a5f', paddingBottom: '16px', marginBottom: '32px', paddingTop: '32px', paddingLeft: '48px', paddingRight: '48px', background: 'linear-gradient(to right, #fff1f2, #ffffff)' }}>
      <div>
        {logoUrl ? (
          <img src={logoUrl} alt={clinicName} style={{ height: '80px', objectFit: 'contain' }} crossOrigin="anonymous" />
        ) : (
          <h1 style={{ fontSize: '30px', fontFamily: 'Georgia, serif', color: '#191c1e', fontWeight: 'bold', margin: 0 }}>{clinicName}</h1>
        )}
      </div>
      <div style={{ textAlign: 'right' }}>
        <h2 style={{ color: '#191c1e', fontSize: '20px', fontWeight: '600', margin: 0 }}>{title}</h2>
        <p style={{ color: '#9ca3af', fontSize: '14px', margin: '4px 0 0 0', fontWeight: '500' }}>Page {pageNum} of {totalPages}</p>
      </div>
    </div>
  );
};

const Footer = ({ reportSettings }) => {
  const isWhiteLabel = reportSettings?.whiteLabel;
  return (
    <div style={{ position: 'absolute', bottom: 0, left: 0, width: '100%', height: '56px', backgroundColor: '#191c1e', display: 'flex', justifyContent: 'space-between', alignItems: 'center', paddingLeft: '48px', paddingRight: '48px', boxSizing: 'border-box' }}>
      <p style={{ color: '#fca5a5', fontSize: '12px', margin: 0, fontWeight: '500' }}>{isWhiteLabel ? 'Generated by Clinic' : 'Generated by SORA Fertility Systems © 2026'}</p>
      <p style={{ color: '#f1f5f9', fontSize: '12px', margin: 0, opacity: 0.8 }}>Not a medical diagnosis. Consult your healthcare provider.</p>
    </div>
  );
};

const PatientDemographics = ({ leadName, formData, results }) => {
  return (
    <div style={{ display: 'flex', gap: '24px', paddingLeft: '48px', paddingRight: '48px', marginBottom: '32px' }}>
      <div style={{ flex: 1, background: 'linear-gradient(135deg, #fff1f2 0%, #ffffff 100%)', padding: '24px', borderRadius: '16px', border: '1px solid #ffe4e6', boxShadow: '0 4px 12px rgba(0,0,0,0.03)' }}>
        <h3 style={{ fontSize: '14px', fontWeight: 'bold', color: '#ff2a5f', textTransform: 'uppercase', letterSpacing: '1px', marginBottom: '16px', borderBottom: '1px solid #ffe4e6', paddingBottom: '8px', marginTop: 0 }}>Patient Profile</h3>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between' }}><span style={{ color: '#64748B', fontSize: '14px' }}>Full Name</span><span style={{ fontWeight: '600', color: '#191c1e' }}>{leadName || 'Patient'}</span></div>
          <div style={{ display: 'flex', justifyContent: 'space-between' }}><span style={{ color: '#64748B', fontSize: '14px' }}>Age</span><span style={{ fontWeight: '600', color: '#191c1e' }}>{formData.age} Years</span></div>
          <div style={{ display: 'flex', justifyContent: 'space-between' }}><span style={{ color: '#64748B', fontSize: '14px' }}>BMI</span><span style={{ fontWeight: '600', color: '#191c1e' }}>{formData.bmi || 'N/A'} kg/m²</span></div>
          <div style={{ display: 'flex', justifyContent: 'space-between' }}><span style={{ color: '#64748B', fontSize: '14px' }}>Current Goal</span><span style={{ fontWeight: '600', color: '#191c1e', textTransform: 'capitalize' }}>{formData.tryingStatus === 'active' ? 'Actively Trying' : formData.tryingStatus}</span></div>
        </div>
      </div>
      <div style={{ flex: 1, background: 'linear-gradient(135deg, #fff1f2 0%, #ffffff 100%)', padding: '24px', borderRadius: '16px', border: '1px solid #ffe4e6', boxShadow: '0 4px 12px rgba(0,0,0,0.03)' }}>
        <h3 style={{ fontSize: '14px', fontWeight: 'bold', color: '#ff2a5f', textTransform: 'uppercase', letterSpacing: '1px', marginBottom: '16px', borderBottom: '1px solid #ffe4e6', paddingBottom: '8px', marginTop: 0 }}>Clinical Triage Result</h3>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between' }}><span style={{ color: '#64748B', fontSize: '14px' }}>Overall Risk Band</span>
            <span style={{ fontWeight: 'bold', textTransform: 'capitalize', color: results.category === 'high' ? '#ff2a5f' : results.category === 'medium' ? '#f59e0b' : '#10b981' }}>
              {results.category}
            </span>
          </div>
          <div style={{ display: 'flex', justifyContent: 'space-between' }}><span style={{ color: '#64748B', fontSize: '14px' }}>Red Markers</span><span style={{ fontWeight: '600', color: '#ff2a5f' }}>{results.redCount}</span></div>
          <div style={{ display: 'flex', justifyContent: 'space-between' }}><span style={{ color: '#64748B', fontSize: '14px' }}>Amber Markers</span><span style={{ fontWeight: '600', color: '#f59e0b' }}>{results.amberCount}</span></div>
          <div style={{ display: 'flex', justifyContent: 'space-between' }}><span style={{ color: '#64748B', fontSize: '14px' }}>Referral Urgency</span><span style={{ fontWeight: '600', color: '#191c1e' }}>{results.urgency.split(' ')[0]}</span></div>
        </div>
      </div>
    </div>
  );
};

export default function PremiumReportTemplate({ results, formData, leadName, reportSettings }) {
  if (!results) return null;

  // --- CHART DATA PREP ---
  const riskColor = results.category === "high" ? "#ff2a5f" : (results.category === "medium" ? "#f59e0b" : "#10b981");
  const riskBg = results.category === "high" ? "#ffe4e6" : (results.category === "medium" ? "#fef3c7" : "#d1fae5");
  
  const gaugeData = [
    { name: 'Score', value: results.category === 'high' ? 85 : results.category === 'medium' ? 50 : 15 },
    { name: 'Remainder', value: results.category === 'high' ? 15 : results.category === 'medium' ? 50 : 85 }
  ];

  const categories = {
    Lifestyle: ['smoking', 'alcohol', 'recreationalDrugs', 'caffeine', 'bmi'],
    Medical: ['thyroid', 'diabetes', 'tbHistory', 'tbTreatment', 'cancerTreatment', 'stiHistory'],
    Menstrual: ['cycleReg', 'cycleLength', 'pcos', 'endo', 'pelvicPain'],
    History: ['prevBirth', 'pregnancyLosses', 'ectopicPregnancy', 'pelvicSurgery', 'uterineHistory', 'familyEarlyMenopause']
  };

  const getCategoryCount = (catName) => {
    return results.flaggedFactors.filter(f => categories[catName]?.includes(f.key)).length;
  };

  const barChartData = [
    { name: 'Lifestyle', count: getCategoryCount('Lifestyle') },
    { name: 'Medical', count: getCategoryCount('Medical') },
    { name: 'Menstrual', count: getCategoryCount('Menstrual') },
    { name: 'History', count: getCategoryCount('History') }
  ];

  const ageData = [
    { age: '25', fertility: 90 },
    { age: '30', fertility: 80 },
    { age: '35', fertility: 60 },
    { age: '38', fertility: 40 },
    { age: '40', fertility: 25 },
    { age: '42', fertility: 10 },
    { age: '45', fertility: 2 },
  ];

  const renderIcon = (level) => {
    if (level === 'red') return <AlertTriangle style={{ color: '#ff2a5f', width: '24px', height: '24px', flexShrink: 0, marginTop: '2px' }} />;
    if (level === 'amber') return <AlertCircle style={{ color: '#f59e0b', width: '24px', height: '24px', flexShrink: 0, marginTop: '2px' }} />;
    return <CheckCircle2 style={{ color: '#10b981', width: '24px', height: '24px', flexShrink: 0, marginTop: '2px' }} />;
  };

  // --- DYNAMIC PAGINATION FOR FLAGGED FACTORS ---
  const chunkedFactors = [];
  const factorsPerPage = 3; // Reduced to 3 factors per page to strictly avoid vertical clipping
  if (results.flaggedFactors.length > 0) {
    for (let i = 0; i < results.flaggedFactors.length; i += factorsPerPage) {
      chunkedFactors.push(results.flaggedFactors.slice(i, i + factorsPerPage));
    }
  } else {
    chunkedFactors.push([]); // Always have at least one chunk for the "no risk factors" message
  }

  // Calculate total pages
  // 1 (Summary) + (1 for Triggers if exist) + chunkedFactors.length (Risk Factor pages) + 1 (Ovarian) + 1 (Action Plan) + 1 (Education) + 1 (Wellness) + 2 (Appendix Split)
  const hasTriggers = results.triggers && results.triggers.length > 0;
  const totalPages = 1 + (hasTriggers ? 1 : 0) + chunkedFactors.length + 1 + 1 + 1 + 1 + 2;
  let currentPage = 1;

  // IMPORTANT: We need to use specific IDs or classes for the html2canvas to correctly parse
  return (
    <div id="premium-report-container" style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', backgroundColor: '#f1f5f9', gap: '20px', padding: '20px' }}>
      
      {/* PAGE 1: Executive Summary */}
      <div className="report-page" style={PAGE_STYLE}>
        <Header pageNum={currentPage++} title="Executive Summary" reportSettings={reportSettings} totalPages={totalPages} />
        <PatientDemographics leadName={leadName} formData={formData} results={results} />

        <div style={{ paddingLeft: '48px', paddingRight: '48px', marginBottom: '32px' }}>
          <div style={{ background: `linear-gradient(135deg, ${riskBg} 0%, #ffffff 100%)`, border: `2px solid ${riskColor}40`, padding: '32px', borderRadius: '16px', display: 'flex', alignItems: 'center', gap: '40px', boxShadow: '0 8px 24px rgba(0,0,0,0.06)' }}>
            <div style={{ width: '33%', display: 'flex', justifyContent: 'center', position: 'relative' }}>
              <PieChart width={200} height={200}>
                <Pie data={gaugeData} cx={100} cy={100} startAngle={180} endAngle={0} innerRadius={70} outerRadius={90} dataKey="value" stroke="none">
                  <Cell fill={riskColor} />
                  <Cell fill="#f1f5f9" />
                </Pie>
              </PieChart>
              <div style={{ position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', paddingTop: '32px' }}>
                <span style={{ fontSize: '30px', fontWeight: 'bold', color: riskColor, textShadow: '0 2px 4px rgba(0,0,0,0.1)' }}>{results.category.toUpperCase()}</span>
                <span style={{ fontSize: '12px', fontWeight: 'bold', color: '#64748B', textTransform: 'uppercase', letterSpacing: '2px', marginTop: '4px' }}>Risk Band</span>
              </div>
            </div>
            <div style={{ width: '66%' }}>
              <h2 style={{ fontSize: '26px', fontFamily: 'Georgia, serif', fontWeight: 'bold', marginBottom: '12px', color: riskColor, marginTop: 0 }}>Clinical Assessment</h2>
              <p style={{ color: '#191c1e', fontSize: '16px', lineHeight: '1.6', marginBottom: '20px', marginTop: 0 }}>{results.detailedMeaning}</p>
              <div style={{ backgroundColor: '#ffffff', padding: '20px', borderRadius: '12px', border: `1px solid ${riskColor}30`, boxShadow: '0 4px 12px rgba(0,0,0,0.04)' }}>
                <p style={{ fontWeight: '600', fontSize: '13px', textTransform: 'uppercase', letterSpacing: '1px', marginBottom: '6px', color: '#64748B', marginTop: 0 }}>Primary Recommendation</p>
                <p style={{ fontWeight: 'bold', color: '#191c1e', fontSize: '18px', margin: 0, lineHeight: '1.4' }}>{results.recommendation}</p>
              </div>
            </div>
          </div>
        </div>
        <Footer reportSettings={reportSettings} />
      </div>

      {/* PAGE 1.5 (Conditional): Immediate Referral Triggers */}
      {hasTriggers && (
        <div className="report-page" style={PAGE_STYLE}>
          <Header pageNum={currentPage++} title="Immediate Referral Triggers" reportSettings={reportSettings} totalPages={totalPages} />
          
          <div style={{ paddingLeft: '48px', paddingRight: '48px', marginBottom: '32px' }}>
            <h3 style={{ fontSize: '22px', fontFamily: 'Georgia, serif', fontWeight: 'bold', color: '#191c1e', borderBottom: '2px solid #e2e8f0', paddingBottom: '8px', marginBottom: '16px', marginTop: 0 }}>Immediate Referral Triggers</h3>
            <p style={{ fontSize: '15px', color: '#475569', marginBottom: '24px', marginTop: 0, lineHeight: '1.6' }}>
              Based on your clinical assessment, we strongly advise consulting a healthcare professional regarding the following findings:
            </p>
            <ul style={{ listStyleType: 'none', padding: 0, margin: 0, display: 'flex', flexDirection: 'column', gap: '16px' }}>
              {results.triggers.map((trigger, idx) => (
                <li key={idx} style={{ display: 'flex', gap: '20px', background: 'linear-gradient(to right, #fff1f2, #ffffff)', padding: '24px', borderRadius: '16px', border: '1px solid #ffe4e6', boxShadow: '0 4px 12px rgba(255, 42, 95, 0.04)' }}>
                  <ShieldAlert style={{ color: '#ff2a5f', flexShrink: 0, width: '28px', height: '28px' }} />
                  <span style={{ color: '#191c1e', fontWeight: '600', fontSize: '18px', lineHeight: '1.4' }}>{trigger}</span>
                </li>
              ))}
            </ul>
          </div>
          
          <Footer reportSettings={reportSettings} />
        </div>
      )}

      {/* PAGE 2(s): Risk Factor Analysis (Chunked) */}
      {chunkedFactors.map((chunk, chunkIndex) => (
        <div key={`risk-page-${chunkIndex}`} className="report-page" style={PAGE_STYLE}>
          <Header pageNum={currentPage++} title={`Risk Factor Analysis ${chunkedFactors.length > 1 ? `(Pt ${chunkIndex + 1})` : ''}`} reportSettings={reportSettings} totalPages={totalPages} />
          
          {chunkIndex === 0 && (
            <div style={{ paddingLeft: '48px', paddingRight: '48px', marginBottom: '32px' }}>
              <h3 style={{ fontSize: '22px', fontFamily: 'Georgia, serif', fontWeight: 'bold', color: '#191c1e', marginBottom: '24px', marginTop: 0 }}>Identified Risk Areas</h3>
              <div style={{ height: '250px', width: '100%', backgroundColor: '#fff1f2', borderRadius: '16px', border: '1px solid #ffe4e6', padding: '16px', boxSizing: 'border-box' }}>
                <BarChart width={600} height={220} data={barChartData} layout="vertical" margin={{ top: 5, right: 30, left: 20, bottom: 5 }}>
                  <CartesianGrid strokeDasharray="3 3" horizontal={false} stroke="#e2e8f0" />
                  <XAxis type="number" allowDecimals={false} stroke="#64748B" />
                  <YAxis dataKey="name" type="category" width={80} tick={{ fill: '#191c1e', fontWeight: 600 }} stroke="#64748B" />
                  <RechartsTooltip cursor={{fill: 'transparent'}} contentStyle={{ borderRadius: '8px', border: 'none', boxShadow: '0 4px 12px rgba(0,0,0,0.1)' }} />
                  <Bar dataKey="count" fill="#fb7185" radius={[0, 4, 4, 0]} barSize={24}>
                    {barChartData.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={entry.count > 1 ? '#ff2a5f' : entry.count === 1 ? '#f59e0b' : '#10b981'} />
                    ))}
                  </Bar>
                </BarChart>
              </div>
            </div>
          )}

          <div style={{ paddingLeft: '48px', paddingRight: '48px' }}>
            <h3 style={{ fontSize: '20px', fontWeight: 'bold', color: '#191c1e', marginBottom: '24px', marginTop: 0 }}>{chunkIndex === 0 ? 'Detailed Marker Breakdown' : 'Detailed Marker Breakdown (Cont.)'}</h3>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
              {chunk.length > 0 ? chunk.map((factor, idx) => (
                <div key={idx} style={{ display: 'flex', alignItems: 'flex-start', gap: '20px', padding: '20px', background: 'linear-gradient(to bottom right, #ffffff, #f8fafc)', borderRadius: '16px', border: '1px solid #e2e8f0', boxShadow: '0 4px 12px rgba(0,0,0,0.02)' }}>
                  <div style={{ padding: '12px', backgroundColor: factor.level === 'red' ? '#fff1f2' : factor.level === 'amber' ? '#fef3c7' : '#d1fae5', borderRadius: '12px' }}>
                    {renderIcon(factor.level)}
                  </div>
                  <div>
                    <h4 style={{ fontWeight: 'bold', color: '#191c1e', fontSize: '18px', margin: 0 }}>{factor.title}</h4>
                    <p style={{ fontSize: '14px', fontWeight: '600', textTransform: 'uppercase', letterSpacing: '1px', marginTop: '6px', marginBottom: '10px', color: factor.level === 'red' ? '#ff2a5f' : '#f59e0b' }}>
                      {factor.label}
                    </p>
                    <p style={{ fontSize: '15px', color: '#475569', lineHeight: '1.6', margin: 0 }}>{factor.detail}</p>
                  </div>
                </div>
              )) : (
                <div style={{ display: 'flex', alignItems: 'center', gap: '16px', padding: '24px', background: 'linear-gradient(to right, #d1fae5, #ffffff)', border: '1px solid #10b981', borderRadius: '16px', color: '#047857', boxShadow: '0 4px 12px rgba(16, 185, 129, 0.05)' }}>
                  <ShieldCheck style={{ width: '32px', height: '32px' }} />
                  <p style={{ fontWeight: 'bold', fontSize: '18px', margin: 0 }}>Excellent! No significant clinical risk markers were identified.</p>
                </div>
              )}
            </div>
          </div>
          <Footer reportSettings={reportSettings} />
        </div>
      ))}

      {/* PAGE 3: Ovarian Reserve & Demographics */}
      <div className="report-page" style={PAGE_STYLE}>
        <Header pageNum={currentPage++} title="Ovarian Reserve & Demographics" reportSettings={reportSettings} totalPages={totalPages} />
        
        {results.ovarianReserve ? (
          <div style={{ paddingLeft: '48px', paddingRight: '48px', marginBottom: '40px' }}>
            <h3 style={{ fontSize: '22px', fontFamily: 'Georgia, serif', fontWeight: 'bold', color: '#191c1e', marginBottom: '20px', marginTop: 0 }}>Laboratory Calibration</h3>
            <div style={{ padding: '32px', background: 'linear-gradient(135deg, #fff1f2 0%, #ffffff 100%)', border: '1px solid #fecdd3', borderRadius: '16px', display: 'flex', alignItems: 'center', gap: '32px', boxShadow: '0 8px 24px rgba(255, 42, 95, 0.05)' }}>
              <div style={{ backgroundColor: '#ff2a5f', padding: '20px', borderRadius: '50%' }}>
                <Activity style={{ width: '48px', height: '48px', color: '#ffffff' }} />
              </div>
              <div>
                <h4 style={{ fontSize: '28px', fontWeight: 'bold', color: '#191c1e', marginTop: '0', marginBottom: '8px', textTransform: 'capitalize' }}>
                  {results.ovarianReserve.reserve} Reserve
                </h4>
                <p style={{ fontSize: '15px', color: '#475569', margin: 0, lineHeight: '1.6' }}>
                  This result is a sophisticated calculation based on your provided AMH, FSH, and AFC inputs. This provides a snapshot of remaining egg quantity, but does not dictate egg quality.
                </p>
              </div>
            </div>
          </div>
        ) : (
          <div style={{ paddingLeft: '48px', paddingRight: '48px', marginBottom: '40px' }}>
            <h3 style={{ fontSize: '22px', fontFamily: 'Georgia, serif', fontWeight: 'bold', color: '#191c1e', marginBottom: '20px', marginTop: 0 }}>Laboratory Calibration</h3>
            <div style={{ padding: '32px', backgroundColor: '#f8fafc', border: '1px dashed #cbd5e1', borderRadius: '16px', display: 'flex', alignItems: 'center', gap: '32px' }}>
              <div style={{ backgroundColor: '#e2e8f0', padding: '20px', borderRadius: '50%' }}>
                <Droplets style={{ width: '40px', height: '40px', color: '#94a3b8' }} />
              </div>
              <div>
                <p style={{ fontSize: '14px', fontWeight: 'bold', color: '#475569', textTransform: 'uppercase', letterSpacing: '1px', margin: '0 0 8px 0' }}>Labs Not Provided</p>
                <p style={{ fontSize: '15px', color: '#64748B', margin: 0, lineHeight: '1.6' }}>Ovarian reserve testing (AMH, FSH, AFC) was skipped. Ask your clinician to perform these simple blood and ultrasound tests to establish your baseline.</p>
              </div>
            </div>
          </div>
        )}

        <div style={{ paddingLeft: '48px', paddingRight: '48px', marginBottom: '40px' }}>
          <h3 style={{ fontSize: '22px', fontFamily: 'Georgia, serif', fontWeight: 'bold', color: '#191c1e', marginBottom: '16px', marginTop: 0 }}>Statistical Fertility Decline by Age</h3>
          <p style={{ fontSize: '15px', color: '#475569', marginBottom: '24px', marginTop: 0, lineHeight: '1.6' }}>
            Female fertility naturally declines with age, primarily due to a decrease in egg quantity and quality. The chart below visualizes the statistical probability of natural conception over a 12-month period relative to your current age ({formData.age}).
          </p>
          <div style={{ height: '320px', width: '100%', background: 'linear-gradient(to bottom, #ffffff, #f8fafc)', border: '1px solid #e2e8f0', borderRadius: '16px', padding: '24px', boxSizing: 'border-box', boxShadow: '0 4px 12px rgba(0,0,0,0.03)' }}>
            <AreaChart width={650} height={260} data={ageData} margin={{ top: 10, right: 30, left: 0, bottom: 0 }}>
              <defs>
                <linearGradient id="colorFertility" x1="0" y1="0" x2="0" y2="1">
                  <stop offset="5%" stopColor="#ff2a5f" stopOpacity={0.6}/>
                  <stop offset="95%" stopColor="#ff2a5f" stopOpacity={0.05}/>
                </linearGradient>
              </defs>
              <XAxis dataKey="age" label={{ value: 'Age', position: 'insideBottomRight', offset: -5 }} stroke="#64748B" />
              <YAxis label={{ value: 'Conception Probability (%)', angle: -90, position: 'insideLeft' }} stroke="#64748B" />
              <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e2e8f0" />
              <Area type="monotone" dataKey="fertility" stroke="#ff2a5f" strokeWidth={4} fillOpacity={1} fill="url(#colorFertility)" />
            </AreaChart>
          </div>
        </div>
        <Footer reportSettings={reportSettings} />
      </div>

      {/* PAGE 4: Action Plan & Timeline */}
      <div className="report-page" style={PAGE_STYLE}>
        <Header pageNum={currentPage++} title="Action Plan & Timeline" reportSettings={reportSettings} totalPages={totalPages} />
        
        <div style={{ paddingLeft: '48px', paddingRight: '48px', marginBottom: '40px' }}>
          <h3 style={{ fontSize: '22px', fontFamily: 'Georgia, serif', fontWeight: 'bold', color: '#191c1e', marginBottom: '32px', marginTop: 0 }}>Recommended Clinical Pathway</h3>
          <div style={{ position: 'relative', borderLeft: '3px solid #fecdd3', marginLeft: '16px', paddingLeft: '40px', display: 'flex', flexDirection: 'column', gap: '40px' }}>
            
            <div style={{ position: 'relative' }}>
              <div style={{ position: 'absolute', left: '-55px', top: '0', width: '24px', height: '24px', backgroundColor: '#ff2a5f', borderRadius: '50%', border: '4px solid #ffffff', boxSizing: 'content-box', boxShadow: '0 2px 8px rgba(0,0,0,0.1)' }} />
              <h4 style={{ fontSize: '20px', fontWeight: 'bold', color: '#191c1e', display: 'flex', alignItems: 'center', gap: '12px', margin: 0 }}><Calendar style={{ width: '24px', height: '24px', color: '#ff2a5f' }}/> Immediate Actions</h4>
              <p style={{ color: '#475569', fontSize: '15px', marginTop: '12px', lineHeight: '1.6', margin: '12px 0 0 0', backgroundColor: '#f8fafc', padding: '16px', borderRadius: '12px', border: '1px solid #e2e8f0' }}>
                {results.category === 'high' ? 
                  "Schedule a consultation with a fertility specialist as soon as possible based on the flagged clinical triggers." : 
                  "Begin preconception vitamins (folic acid) and review lifestyle factors identified in the risk analysis."}
              </p>
            </div>
            
            <div style={{ position: 'relative' }}>
              <div style={{ position: 'absolute', left: '-55px', top: '0', width: '24px', height: '24px', backgroundColor: '#ff2a5f', borderRadius: '50%', border: '4px solid #ffffff', boxSizing: 'content-box', boxShadow: '0 2px 8px rgba(0,0,0,0.1)' }} />
              <h4 style={{ fontSize: '20px', fontWeight: 'bold', color: '#191c1e', display: 'flex', alignItems: 'center', gap: '12px', margin: 0 }}><Activity style={{ width: '24px', height: '24px', color: '#ff2a5f' }}/> 3-6 Months</h4>
              <p style={{ color: '#475569', fontSize: '15px', marginTop: '12px', lineHeight: '1.6', margin: '12px 0 0 0', backgroundColor: '#f8fafc', padding: '16px', borderRadius: '12px', border: '1px solid #e2e8f0' }}>
                If conception has not occurred, or if you are planning for the future, consider baseline hormone testing (AMH, FSH) and a pelvic ultrasound. {formData.partnerSperm !== 'yes' && "A partner semen analysis should also be performed."}
              </p>
            </div>
            
            <div style={{ position: 'relative' }}>
              <div style={{ position: 'absolute', left: '-55px', top: '0', width: '24px', height: '24px', backgroundColor: '#ff2a5f', borderRadius: '50%', border: '4px solid #ffffff', boxSizing: 'content-box', boxShadow: '0 2px 8px rgba(0,0,0,0.1)' }} />
              <h4 style={{ fontSize: '20px', fontWeight: 'bold', color: '#191c1e', display: 'flex', alignItems: 'center', gap: '12px', margin: 0 }}><Stethoscope style={{ width: '24px', height: '24px', color: '#ff2a5f' }}/> 6-12 Months</h4>
              <p style={{ color: '#475569', fontSize: '15px', marginTop: '12px', lineHeight: '1.6', margin: '12px 0 0 0', backgroundColor: '#f8fafc', padding: '16px', borderRadius: '12px', border: '1px solid #e2e8f0' }}>
                A full specialist intervention may be necessary. Depending on ovarian reserve and age, treatments such as IUI or IVF might be discussed to maximize chances of success.
              </p>
            </div>
          </div>
        </div>

        <div style={{ paddingLeft: '48px', paddingRight: '48px' }}>
          <h3 style={{ fontSize: '22px', fontFamily: 'Georgia, serif', fontWeight: 'bold', color: '#191c1e', marginBottom: '24px', marginTop: 0 }}>Preconception Checklist</h3>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px' }}>
            <div style={{ padding: '20px', background: 'linear-gradient(to bottom, #ffffff, #fff1f2)', border: '1px solid #ffe4e6', borderRadius: '16px', display: 'flex', gap: '16px', boxShadow: '0 4px 12px rgba(0,0,0,0.03)' }}>
              <div style={{ backgroundColor: '#ffe4e6', padding: '10px', borderRadius: '10px', height: 'fit-content' }}>
                <HeartPulse style={{ width: '24px', height: '24px', color: '#ff2a5f' }} />
              </div>
              <div>
                <span style={{ fontWeight: 'bold', display: 'block', fontSize: '16px', color: '#191c1e' }}>Prenatal Vitamins</span>
                <span style={{ fontSize: '13px', color: '#64748B', display: 'block', marginTop: '6px', lineHeight: '1.5' }}>Take at least 400mcg of Folic Acid daily to prevent neural tube defects.</span>
              </div>
            </div>
            <div style={{ padding: '20px', background: 'linear-gradient(to bottom, #ffffff, #fff1f2)', border: '1px solid #ffe4e6', borderRadius: '16px', display: 'flex', gap: '16px', boxShadow: '0 4px 12px rgba(0,0,0,0.03)' }}>
              <div style={{ backgroundColor: '#ffe4e6', padding: '10px', borderRadius: '10px', height: 'fit-content' }}>
                <Calendar style={{ width: '24px', height: '24px', color: '#ff2a5f' }} />
              </div>
              <div>
                <span style={{ fontWeight: 'bold', display: 'block', fontSize: '16px', color: '#191c1e' }}>Cycle Tracking</span>
                <span style={{ fontSize: '13px', color: '#64748B', display: 'block', marginTop: '6px', lineHeight: '1.5' }}>Monitor your cycles and ovulation to identify your fertile window.</span>
              </div>
            </div>
            <div style={{ padding: '20px', background: 'linear-gradient(to bottom, #ffffff, #fff1f2)', border: '1px solid #ffe4e6', borderRadius: '16px', display: 'flex', gap: '16px', boxShadow: '0 4px 12px rgba(0,0,0,0.03)' }}>
              <div style={{ backgroundColor: '#ffe4e6', padding: '10px', borderRadius: '10px', height: 'fit-content' }}>
                <AlertCircle style={{ width: '24px', height: '24px', color: '#ff2a5f' }} />
              </div>
              <div>
                <span style={{ fontWeight: 'bold', display: 'block', fontSize: '16px', color: '#191c1e' }}>Lifestyle Optimization</span>
                <span style={{ fontSize: '13px', color: '#64748B', display: 'block', marginTop: '6px', lineHeight: '1.5' }}>Limit caffeine, reduce alcohol, and aim for a balanced BMI.</span>
              </div>
            </div>
            <div style={{ padding: '20px', background: 'linear-gradient(to bottom, #ffffff, #fff1f2)', border: '1px solid #ffe4e6', borderRadius: '16px', display: 'flex', gap: '16px', boxShadow: '0 4px 12px rgba(0,0,0,0.03)' }}>
              <div style={{ backgroundColor: '#ffe4e6', padding: '10px', borderRadius: '10px', height: 'fit-content' }}>
                <Stethoscope style={{ width: '24px', height: '24px', color: '#ff2a5f' }} />
              </div>
              <div>
                <span style={{ fontWeight: 'bold', display: 'block', fontSize: '16px', color: '#191c1e' }}>Medical Review</span>
                <span style={{ fontSize: '13px', color: '#64748B', display: 'block', marginTop: '6px', lineHeight: '1.5' }}>Manage chronic conditions like Thyroid issues or Diabetes.</span>
              </div>
            </div>
          </div>
        </div>
        <Footer reportSettings={reportSettings} />
      </div>

      {/* PAGE 5: Fertility 101 Educational Section */}
      <div className="report-page" style={PAGE_STYLE}>
        <Header pageNum={currentPage++} title="Fertility 101: Educational Guide" reportSettings={reportSettings} totalPages={totalPages} />
        
        <div style={{ paddingLeft: '48px', paddingRight: '48px', marginBottom: '32px' }}>
          <h3 style={{ fontSize: '22px', fontFamily: 'Georgia, serif', fontWeight: 'bold', color: '#191c1e', marginBottom: '20px', marginTop: 0 }}>Understanding Your Biology</h3>
          <p style={{ fontSize: '15px', color: '#475569', lineHeight: '1.6', marginBottom: '24px', marginTop: 0 }}>Knowledge is power when it comes to your reproductive health. Here are the core concepts every individual should understand about their fertility journey.</p>
          
          <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
            <div style={{ padding: '24px', background: 'linear-gradient(to right, #191c1e, #334155)', color: '#ffffff', borderRadius: '16px', display: 'flex', gap: '20px', boxShadow: '0 8px 16px rgba(15, 23, 42, 0.15)' }}>
              <BookOpen style={{ width: '32px', height: '32px', color: '#fca5a5', flexShrink: 0 }} />
              <div>
                <h4 style={{ fontSize: '18px', fontWeight: 'bold', color: '#fca5a5', margin: '0 0 8px 0' }}>The Menstrual Cycle & Ovulation</h4>
                <p style={{ fontSize: '14px', margin: 0, lineHeight: '1.6', color: '#f1f5f9' }}>A typical cycle lasts 28 days, though 21-35 days is considered normal. Ovulation usually occurs around day 14. An egg survives for only 12-24 hours after release, making the "fertile window" (the 5 days before and the day of ovulation) critical for conception.</p>
              </div>
            </div>

            <div style={{ padding: '24px', background: '#f8fafc', border: '1px solid #cbd5e1', borderRadius: '16px', display: 'flex', gap: '20px' }}>
              <Activity style={{ width: '32px', height: '32px', color: '#ff2a5f', flexShrink: 0 }} />
              <div>
                <h4 style={{ fontSize: '18px', fontWeight: 'bold', color: '#191c1e', margin: '0 0 8px 0' }}>Ovarian Reserve: Quantity vs. Quality</h4>
                <p style={{ fontSize: '14px', margin: 0, lineHeight: '1.6', color: '#475569' }}><strong>Quantity:</strong> Measured by AMH and AFC, this tells us roughly how many eggs remain. It dictates how you might respond to IVF medications.<br/><br/><strong>Quality:</strong> Cannot be measured by a blood test. Age is the only true proxy for egg quality. As women age, the percentage of genetically normal eggs naturally decreases.</p>
              </div>
            </div>

            <div style={{ padding: '24px', background: '#f8fafc', border: '1px solid #cbd5e1', borderRadius: '16px', display: 'flex', gap: '20px' }}>
              <Sparkles style={{ width: '32px', height: '32px', color: '#ff2a5f', flexShrink: 0 }} />
              <div>
                <h4 style={{ fontSize: '18px', fontWeight: 'bold', color: '#191c1e', margin: '0 0 8px 0' }}>The Male Factor</h4>
                <p style={{ fontSize: '14px', margin: 0, lineHeight: '1.6', color: '#475569' }}>It takes two to conceive! Male factor infertility contributes to roughly 40-50% of all infertility cases. A simple semen analysis can evaluate sperm count, motility (movement), and morphology (shape). It is highly recommended that partners get tested early in the process.</p>
              </div>
            </div>
          </div>
        </div>
        <Footer reportSettings={reportSettings} />
      </div>

      {/* PAGE 6: Personalized Wellness Plan */}
      <div className="report-page" style={PAGE_STYLE}>
        <Header pageNum={currentPage++} title="Lifestyle & Wellness Plan" reportSettings={reportSettings} totalPages={totalPages} />
        
        <div style={{ paddingLeft: '48px', paddingRight: '48px', marginBottom: '32px' }}>
          <h3 style={{ fontSize: '22px', fontFamily: 'Georgia, serif', fontWeight: 'bold', color: '#191c1e', marginBottom: '24px', marginTop: 0 }}>Optimizing Your Body for Conception</h3>
          
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '24px' }}>
            <div style={{ padding: '24px', backgroundColor: '#ffffff', border: '1px solid #e2e8f0', borderRadius: '16px', boxShadow: '0 4px 12px rgba(0,0,0,0.03)' }}>
              <Apple style={{ width: '28px', height: '28px', color: '#ff2a5f', marginBottom: '16px' }} />
              <h4 style={{ fontSize: '18px', fontWeight: 'bold', color: '#191c1e', margin: '0 0 12px 0' }}>Nutrition & Diet</h4>
              <ul style={{ paddingLeft: '20px', margin: 0, color: '#64748B', fontSize: '14px', lineHeight: '1.6' }}>
                <li style={{ marginBottom: '8px' }}><strong>Folic Acid/Folate:</strong> Essential for neural tube development.</li>
                <li style={{ marginBottom: '8px' }}><strong>Antioxidants:</strong> Berries, nuts, and dark leafy greens help protect egg quality.</li>
                <li><strong>Omega-3s:</strong> Found in salmon and walnuts, supportive of reproductive hormone production.</li>
              </ul>
            </div>

            <div style={{ padding: '24px', backgroundColor: '#ffffff', border: '1px solid #e2e8f0', borderRadius: '16px', boxShadow: '0 4px 12px rgba(0,0,0,0.03)' }}>
              <Moon style={{ width: '28px', height: '28px', color: '#ff2a5f', marginBottom: '16px' }} />
              <h4 style={{ fontSize: '18px', fontWeight: 'bold', color: '#191c1e', margin: '0 0 12px 0' }}>Sleep & Circadian Rhythm</h4>
              <ul style={{ paddingLeft: '20px', margin: 0, color: '#64748B', fontSize: '14px', lineHeight: '1.6' }}>
                <li style={{ marginBottom: '8px' }}><strong>Melatonin:</strong> Critical for sleep, but also found in follicular fluid where it protects eggs from oxidative stress.</li>
                <li style={{ marginBottom: '8px' }}>Aim for 7-9 hours of uninterrupted sleep.</li>
                <li>Minimize blue light exposure 1 hour before bed to support natural hormone cycles.</li>
              </ul>
            </div>

            <div style={{ padding: '24px', backgroundColor: '#ffffff', border: '1px solid #e2e8f0', borderRadius: '16px', boxShadow: '0 4px 12px rgba(0,0,0,0.03)' }}>
              <Sun style={{ width: '28px', height: '28px', color: '#ff2a5f', marginBottom: '16px' }} />
              <h4 style={{ fontSize: '18px', fontWeight: 'bold', color: '#191c1e', margin: '0 0 12px 0' }}>Stress Management</h4>
              <ul style={{ paddingLeft: '20px', margin: 0, color: '#64748B', fontSize: '14px', lineHeight: '1.6' }}>
                <li style={{ marginBottom: '8px' }}>High cortisol levels can disrupt the hypothalamus, which regulates ovulation.</li>
                <li style={{ marginBottom: '8px' }}>Incorporate mindfulness, yoga, or deep breathing exercises into your daily routine.</li>
              </ul>
            </div>

            <div style={{ padding: '24px', backgroundColor: '#ffffff', border: '1px solid #e2e8f0', borderRadius: '16px', boxShadow: '0 4px 12px rgba(0,0,0,0.03)' }}>
              <Leaf style={{ width: '28px', height: '28px', color: '#ff2a5f', marginBottom: '16px' }} />
              <h4 style={{ fontSize: '18px', fontWeight: 'bold', color: '#191c1e', margin: '0 0 12px 0' }}>Environmental Toxins</h4>
              <ul style={{ paddingLeft: '20px', margin: 0, color: '#64748B', fontSize: '14px', lineHeight: '1.6' }}>
                <li style={{ marginBottom: '8px' }}><strong>Endocrine Disruptors:</strong> Avoid BPA (plastics) and Phthalates (fragrances/cosmetics) which can mimic hormones.</li>
                <li>Switch to glass food containers and clean, non-toxic household products where possible.</li>
              </ul>
            </div>
          </div>
        </div>
        <Footer reportSettings={reportSettings} />
      </div>

      {/* PAGE 7: Appendix - Glossary */}
      <div className="report-page" style={{ ...PAGE_STYLE, backgroundColor: '#f8fafc' }}>
        <Header pageNum={currentPage++} title="Appendix: Glossary" reportSettings={reportSettings} totalPages={totalPages} />
        
        <div style={{ paddingLeft: '48px', paddingRight: '48px', marginBottom: '40px' }}>
          <h3 style={{ fontSize: '22px', fontFamily: 'Georgia, serif', fontWeight: 'bold', color: '#191c1e', marginBottom: '24px', marginTop: 0 }}>Medical Glossary</h3>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
            <div style={{ backgroundColor: '#ffffff', padding: '24px', borderRadius: '16px', border: '1px solid #e2e8f0', boxShadow: '0 4px 12px rgba(0,0,0,0.02)' }}>
              <h4 style={{ fontWeight: 'bold', color: '#ff2a5f', margin: 0, fontSize: '16px' }}>AMH (Anti-Müllerian Hormone)</h4>
              <p style={{ fontSize: '15px', color: '#475569', margin: '8px 0 0 0', lineHeight: '1.6' }}>A hormone produced by small follicles in the ovaries. It is used as an indicator of ovarian reserve (the number of eggs remaining).</p>
            </div>
            <div style={{ backgroundColor: '#ffffff', padding: '24px', borderRadius: '16px', border: '1px solid #e2e8f0', boxShadow: '0 4px 12px rgba(0,0,0,0.02)' }}>
              <h4 style={{ fontWeight: 'bold', color: '#ff2a5f', margin: 0, fontSize: '16px' }}>FSH (Follicle-Stimulating Hormone)</h4>
              <p style={{ fontSize: '15px', color: '#475569', margin: '8px 0 0 0', lineHeight: '1.6' }}>A hormone that stimulates the growth of ovarian follicles. Elevated baseline levels often indicate diminishing ovarian reserve.</p>
            </div>
            <div style={{ backgroundColor: '#ffffff', padding: '24px', borderRadius: '16px', border: '1px solid #e2e8f0', boxShadow: '0 4px 12px rgba(0,0,0,0.02)' }}>
              <h4 style={{ fontWeight: 'bold', color: '#ff2a5f', margin: 0, fontSize: '16px' }}>PCOS (Polycystic Ovary Syndrome)</h4>
              <p style={{ fontSize: '15px', color: '#475569', margin: '8px 0 0 0', lineHeight: '1.6' }}>A common hormonal disorder that can cause irregular periods, excess androgen levels, and polycystic ovaries, often impacting ovulation.</p>
            </div>
            <div style={{ backgroundColor: '#ffffff', padding: '24px', borderRadius: '16px', border: '1px solid #e2e8f0', boxShadow: '0 4px 12px rgba(0,0,0,0.02)' }}>
              <h4 style={{ fontWeight: 'bold', color: '#ff2a5f', margin: 0, fontSize: '16px' }}>Ovarian Reserve</h4>
              <p style={{ fontSize: '15px', color: '#475569', margin: '8px 0 0 0', lineHeight: '1.6' }}>A term used to describe the reproductive potential left in a woman's two ovaries based on the number and quality of remaining eggs.</p>
            </div>
          </div>
        </div>

        <Footer reportSettings={reportSettings} />
      </div>

      {/* PAGE 8: Appendix - Legal & References */}
      <div className="report-page" style={{ ...PAGE_STYLE, backgroundColor: '#f8fafc' }}>
        <Header pageNum={currentPage++} title="Appendix: References & Legal" reportSettings={reportSettings} totalPages={totalPages} />

        <div style={{ paddingLeft: '48px', paddingRight: '48px', marginBottom: '32px' }}>
          <h3 style={{ fontSize: '20px', fontWeight: 'bold', color: '#191c1e', marginBottom: '16px', marginTop: 0 }}>Clinical References</h3>
          <ul style={{ paddingLeft: '20px', margin: 0, color: '#475569', fontSize: '13px', lineHeight: '1.6' }}>
            <li style={{ marginBottom: '6px' }}>Practice Committee of the ASRM. (2015). Testing and interpreting measures of ovarian reserve: a committee opinion. <em>Fertility and Sterility</em>.</li>
            <li style={{ marginBottom: '6px' }}>ESHRE Capri Workshop Group. (2010). Europe the continent with the lowest fertility. <em>Human Reproduction Update</em>.</li>
            <li style={{ marginBottom: '6px' }}>Bunting, L., & Boivin, J. (2010). Development and preliminary validation of the fertility status awareness tool (FertiSTAT). <em>Human Reproduction</em>, 25(7), 1722-1733.</li>
            <li style={{ marginBottom: '6px' }}>Somigliana, E., et al. (2016). IVF-ICSI outcome in women with unoperated endometriosis. <em>Human Reproduction Update</em>.</li>
          </ul>
        </div>

        <div style={{ paddingLeft: '48px', paddingRight: '48px', marginBottom: '40px' }}>
          <h3 style={{ fontSize: '16px', fontWeight: 'bold', color: '#191c1e', marginBottom: '12px', marginTop: 0 }}>Legal & Medical Disclaimer</h3>
          <div style={{ backgroundColor: '#f1f5f9', padding: '16px', borderRadius: '12px', color: '#64748B', fontSize: '12px', lineHeight: '1.5', border: '1px solid #e2e8f0' }}>
            <p style={{ margin: '0 0 8px 0' }}><strong>Not Medical Advice:</strong> This report is generated by an automated algorithmic assessment and is intended strictly for educational and informational purposes. It does not constitute medical advice, diagnosis, or treatment.</p>
            <p style={{ margin: '0 0 8px 0' }}><strong>No Doctor-Patient Relationship:</strong> The use of the SORA Fertility assessment does not create a doctor-patient relationship. You should not rely on this information as a substitute for professional medical guidance.</p>
            <p style={{ margin: 0 }}><strong>Consult Your Healthcare Provider:</strong> Always seek the advice of your physician, reproductive endocrinologist, or other qualified health provider with any questions you may have regarding a medical condition or treatment plan. Never disregard professional medical advice or delay in seeking it because of something you have read in this report.</p>
          </div>
        </div>

        <div style={{ position: 'absolute', bottom: '80px', left: '48px', right: '48px', background: 'linear-gradient(135deg, #191c1e 0%, #334155 100%)', padding: '32px', borderRadius: '20px', textAlign: 'center', boxShadow: '0 12px 32px rgba(15, 23, 42, 0.2)' }}>
          <FileText style={{ width: '40px', height: '40px', color: '#fca5a5', margin: '0 auto 16px auto', display: 'block' }} />
          <img src="/sora-logo.png" alt="SORA Fertility" style={{ width: '160px', height: 'auto', marginBottom: '16px', filter: 'brightness(0) invert(1)' }} />
          <p style={{ color: '#cbd5e1', fontSize: '14px', maxWidth: '450px', margin: '0 auto', lineHeight: '1.6' }}>
            Empowering your reproductive journey with evidence-based insights.
          </p>
        </div>

        <Footer reportSettings={reportSettings} />
      </div>

    </div>
  );
}
