import React, { useEffect, useState } from 'react';
import { Download, CheckCircle2, AlertTriangle, AlertCircle, Sparkles } from 'lucide-react';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';

const PAGE_STYLE = {
  width: '794px',
  height: '1123px',
  backgroundColor: '#ffffff',
  position: 'relative',
  overflow: 'hidden',
  boxSizing: 'border-box',
  fontFamily: 'system-ui, -apple-system, sans-serif',
  margin: '0 auto 20px auto',
  padding: '0',
  boxShadow: '0 4px 12px rgba(0,0,0,0.1)'
};

const Header = ({ pageNum, title, totalPages = 2 }) => (
  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', borderBottom: '3px solid #ff2a5f', paddingBottom: '16px', marginBottom: '32px', paddingTop: '32px', paddingLeft: '48px', paddingRight: '48px', background: 'linear-gradient(to right, #fff1f2, #ffffff)' }}>
    <div>
      <h1 style={{ fontSize: '30px', fontFamily: 'Georgia, serif', color: '#191c1e', fontWeight: 'bold', margin: 0 }}>SORA PCOS Assessment</h1>
    </div>
    <div style={{ textAlign: 'right' }}>
      <h2 style={{ color: '#191c1e', fontSize: '20px', fontWeight: '600', margin: 0 }}>{title}</h2>
      <p style={{ color: '#9ca3af', fontSize: '14px', margin: '4px 0 0 0', fontWeight: '500' }}>Page {pageNum} of {totalPages}</p>
    </div>
  </div>
);

const Footer = () => (
  <div style={{ position: 'absolute', bottom: 0, left: 0, width: '100%', height: '56px', backgroundColor: '#191c1e', display: 'flex', justifyContent: 'space-between', alignItems: 'center', paddingLeft: '48px', paddingRight: '48px', boxSizing: 'border-box' }}>
    <p style={{ color: '#fca5a5', fontSize: '12px', margin: 0, fontWeight: '500' }}>Generated by SORA Fertility Systems © 2026</p>
    <p style={{ color: '#f1f5f9', fontSize: '12px', margin: 0, opacity: 0.8 }}>Not a medical diagnosis. Consult your healthcare provider.</p>
  </div>
);

export default function PcosReportTemplate({ assessment, patientData, onClose }) {
  const [downloading, setDownloading] = useState(false);

  if (!assessment) return null;

  const riskColor = assessment.category === "Very high likelihood" ? "#ff2a5f" : 
                    assessment.category === "High likelihood" ? "#f97316" : 
                    assessment.category === "Moderate likelihood" ? "#f59e0b" : "#10b981";

  const handleDownload = async () => {
    setDownloading(true);
    try {
      const elements = document.querySelectorAll('.report-page');
      const pdf = new jsPDF('p', 'pt', 'a4');

      for (let i = 0; i < elements.length; i++) {
        const canvas = await html2canvas(elements[i], { scale: 2 });
        const imgData = canvas.toDataURL('image/jpeg', 1.0);
        if (i > 0) pdf.addPage();
        pdf.addImage(imgData, 'JPEG', 0, 0, 595.28, 841.89);
      }
      pdf.save(`SORA_PCOS_Report_${patientData.name || 'Patient'}.pdf`);
    } catch (e) {
      console.error(e);
      alert("Failed to download PDF.");
    } finally {
      setDownloading(false);
    }
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', backgroundColor: '#f1f5f9', padding: '20px', gap: '20px', width: '100%', overflowY: 'auto' }}>
      
      <div style={{ display: 'flex', justifyContent: 'center', width: '100%', marginBottom: '20px', marginTop: '40px' }}>
        <button onClick={handleDownload} disabled={downloading} style={{ padding: '12px 24px', background: '#2563eb', color: 'white', border: 'none', borderRadius: '12px', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '8px', fontSize: '16px', fontWeight: 'bold', boxShadow: '0 4px 12px rgba(37,99,235,0.3)' }}>
          <Download size={20} /> {downloading ? "Generating PDF..." : "Download PDF Report"}
        </button>
      </div>

      <div id="pcos-report-container" style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
        {/* PAGE 1: Summary */}
        <div className="report-page" style={PAGE_STYLE}>
          <Header pageNum={1} title="Executive Summary" totalPages={2} />
          
          <div style={{ paddingLeft: '48px', paddingRight: '48px', marginBottom: '32px' }}>
            <div style={{ background: '#f8fafc', padding: '24px', borderRadius: '16px', border: '1px solid #e2e8f0', display: 'flex', justifyContent: 'space-between' }}>
              <div><span style={{ color: '#64748B' }}>Patient:</span> <strong style={{color: '#1e293b'}}>{patientData.name}</strong></div>
              <div><span style={{ color: '#64748B' }}>Age:</span> <strong style={{color: '#1e293b'}}>{patientData.age}</strong></div>
              <div><span style={{ color: '#64748B' }}>BMI:</span> <strong style={{color: '#1e293b'}}>{patientData.bmi}</strong></div>
            </div>
          </div>

          <div style={{ paddingLeft: '48px', paddingRight: '48px', marginBottom: '32px' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '32px', background: '#fff', border: `2px solid ${riskColor}`, padding: '32px', borderRadius: '16px' }}>
              <div>
                <div style={{ fontSize: '48px', fontWeight: 'bold', color: riskColor }}>{assessment.score} <span style={{fontSize: '16px', color: '#64748B'}}>/ 100</span></div>
                <div style={{ fontSize: '18px', fontWeight: 'bold', textTransform: 'uppercase', color: riskColor, marginTop: '8px' }}>{assessment.category}</div>
              </div>
              <div style={{ borderLeft: '1px solid #e2e8f0', paddingLeft: '32px' }}>
                <h2 style={{ margin: '0 0 12px 0', fontSize: '22px' }}>Clinical Explanation</h2>
                <p style={{ margin: 0, color: '#475569', lineHeight: '1.6' }}>{assessment.explanation}</p>
              </div>
            </div>
          </div>

          <div style={{ paddingLeft: '48px', paddingRight: '48px' }}>
            <h3 style={{ fontSize: '20px', borderBottom: '2px solid #e2e8f0', paddingBottom: '8px', marginBottom: '16px' }}>Major Contributing Factors</h3>
            <ul style={{ listStyle: 'none', padding: 0, display: 'flex', flexDirection: 'column', gap: '12px' }}>
              {assessment.contributingFactors?.map((factor, i) => (
                <li key={i} style={{ padding: '16px', background: '#fff1f2', borderRadius: '8px', color: '#ff2a5f', fontWeight: '600' }}>
                  <AlertTriangle size={18} style={{ display: 'inline', marginRight: '8px', verticalAlign: 'middle' }}/>
                  {factor}
                </li>
              ))}
              {assessment.contributingFactors?.length === 0 && (
                <li style={{ padding: '16px', background: '#d1fae5', borderRadius: '8px', color: '#047857', fontWeight: '600' }}>
                  No major contributing factors identified.
                </li>
              )}
            </ul>
          </div>
          <Footer />
        </div>

        {/* PAGE 2: Insights and Plan */}
        <div className="report-page" style={PAGE_STYLE}>
          <Header pageNum={2} title="Insights & Next Steps" totalPages={2} />
          
          <div style={{ paddingLeft: '48px', paddingRight: '48px', marginBottom: '32px' }}>
            <h3 style={{ fontSize: '20px', borderBottom: '2px solid #e2e8f0', paddingBottom: '8px', marginBottom: '16px' }}>Pattern Insights</h3>
            {assessment.patternInsights?.length > 0 ? (
              <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
                {assessment.patternInsights.map((pattern, i) => (
                  <div key={i} style={{ padding: '20px', background: '#f8fafc', border: '1px solid #cbd5e1', borderRadius: '12px', display: 'flex', gap: '16px' }}>
                    <Sparkles style={{ color: '#2563eb', width: '24px', height: '24px' }} />
                    <span style={{ fontSize: '16px', fontWeight: '600', color: '#1e293b' }}>{pattern}</span>
                  </div>
                ))}
              </div>
            ) : (
              <p style={{ color: '#475569' }}>No specific sub-patterns identified based on your responses.</p>
            )}
          </div>

          <div style={{ paddingLeft: '48px', paddingRight: '48px', marginBottom: '32px' }}>
            <h3 style={{ fontSize: '20px', borderBottom: '2px solid #e2e8f0', paddingBottom: '8px', marginBottom: '16px' }}>Recommended Next Steps</h3>
            <div style={{ padding: '24px', background: '#e0f2fe', borderRadius: '12px', border: '1px solid #bae6fd' }}>
              <p style={{ margin: 0, fontSize: '16px', color: '#0369a1', lineHeight: '1.6', fontWeight: '500' }}>{assessment.nextSteps}</p>
            </div>
          </div>

          <div style={{ position: 'absolute', bottom: '80px', left: '48px', right: '48px', background: '#191c1e', padding: '32px', borderRadius: '16px', textAlign: 'center' }}>
            <h2 style={{ color: '#ffffff', fontSize: '22px', margin: '0 0 8px 0' }}>SORA Fertility</h2>
            <p style={{ color: '#cbd5e1', fontSize: '14px', margin: 0 }}>Empowering your reproductive journey with evidence-based insights.</p>
          </div>
          <Footer />
        </div>
      </div>
    </div>
  );
}
