import { NextResponse } from "next/server";
import { generatePregnancyTimelinePDF } from "../../../lib/pdfGenerator";
import nodemailer from "nodemailer";

export async function POST(req) {
  try {
    const { results, email, insights } = await req.json();

    if (!results) {
      return NextResponse.json({ error: "Missing calculation results" }, { status: 400 });
    }

    // Generate PDF buffer
    const pdfBuffer = await generatePregnancyTimelinePDF(results, insights);

    // If an email is provided, send it
    if (email) {
      const transporter = nodemailer.createTransport({
        host: process.env.SMTP_HOST || "smtp.gmail.com",
        port: parseInt(process.env.SMTP_PORT) || 587,
        secure: parseInt(process.env.SMTP_PORT) === 465,
        auth: {
          user: process.env.SMTP_USER,
          pass: process.env.SMTP_PASS,
        },
      });

      await transporter.sendMail({
        from: process.env.SMTP_FROM || '"SORA Fertility" <noreply@sorafertility.com>',
        to: email,
        subject: "Your SORA Pregnancy Timeline & Due Date Report",
        text: `Congratulations on your pregnancy!\n\nPlease find attached your personalized Pregnancy Timeline and Estimated Due Date report, generated by SORA.\n\nYour Estimated Due Date is: ${results.dueDate}\n\nWarmly,\nThe SORA Team`,
        html: `
          <div style="font-family: sans-serif; color: #333; max-width: 600px; margin: 0 auto; line-height: 1.6;">
            <h2 style="color: #ff2a5f;">Congratulations! 🎉</h2>
            <p>Please find attached your personalized Pregnancy Timeline and Estimated Due Date report, generated by the SORA Due Date Calculator.</p>
            <div style="background: #fff1f2; padding: 20px; border-radius: 12px; margin: 20px 0; border-left: 4px solid #ff2a5f;">
              <strong>Estimated Due Date:</strong> <span style="color: #ff2a5f; font-size: 1.1em;">${results.dueDate}</span><br/>
              <strong>Current Gestational Age:</strong> ${results.gestationalAge}
            </div>
            <p>Warmly,<br/><strong>The SORA Team</strong></p>
          </div>
        `,
        attachments: [
          {
            filename: "SORA_Pregnancy_Timeline.pdf",
            content: pdfBuffer,
          },
        ],
      });

      return NextResponse.json({ success: true, message: "Email sent successfully" });
    }

    // If no email, return the PDF directly for download
    return new NextResponse(pdfBuffer, {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': 'attachment; filename="SORA_Pregnancy_Timeline.pdf"',
      },
    });
  } catch (error) {
    console.error("Due Date API Error:", error?.message || error);
    return NextResponse.json({ error: error?.message || "Internal Server Error" }, { status: 500 });
  }
}
